package types

import "regexp"

// Code generated by generate_heuristics.go. DO NOT EDIT.

// NOTE:
// GitHub Linguist contains a few Ruby-specific regexes (lookbehind/lookahead)
// that are incompatible with Go's regexp (RE2). Those heuristics have been
// omitted from the generated map.

var HeuristicMap = map[string][]HeuristicRule{

	"1": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\.(?:[A-Za-z]{2}(?:\\s|$)|\\\\\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"1in": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"1m": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"1x": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"2": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\.(?:[A-Za-z]{2}(?:\\s|$)|\\\\\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"3": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\.(?:[A-Za-z]{2}(?:\\s|$)|\\\\\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"3in": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"3m": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"3p": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"3pm": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"3qt": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"3x": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"4": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\.(?:[A-Za-z]{2}(?:\\s|$)|\\\\\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"5": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\.(?:[A-Za-z]{2}(?:\\s|$)|\\\\\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"6": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\.(?:[A-Za-z]{2}(?:\\s|$)|\\\\\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"7": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\.(?:[A-Za-z]{2}(?:\\s|$)|\\\\\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"8": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\.(?:[A-Za-z]{2}(?:\\s|$)|\\\\\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"9": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\.(?:[A-Za-z]{2}(?:\\s|$)|\\\\\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"action": {
		{
			Language: "ROS Interface",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^[a-z]\\w*(?:\\/[a-z]\\w*)?(?:<=\\d+)?(?:\\[(?:<=\\d+)?\\])?\\s+\\w+\\b"),
				regexp.MustCompile("^---\\s*$"),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^\\s*[^\\s@#\\w-]"),
			},
		},
	},
	"al": {
		{
			Language: "AL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\b(?i:(CODEUNIT|PAGE|PAGEEXTENSION|PAGECUSTOMIZATION|DOTNET|ENUM|ENUMEXTENSION|VALUE|QUERY|REPORT|TABLE|TABLEEXTENSION|XMLPORT|PROFILE|CONTROLADDIN|REPORTEXTENSION|INTERFACE|PERMISSIONSET|PERMISSIONSETEXTENSION|ENTITLEMENT))\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Perl",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"alg": {
		{
			Language: "ALGOL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^comment\\b.*(;|comment)"),
				regexp.MustCompile("^#[^#\\r\\n]+#$"),
				regexp.MustCompile("(?i)\\b(integer|real|boolean|string)\\b\\s+\\w+\\s*:=\\s*"),
				regexp.MustCompile("(?i)^begin[\\s\\S]*^end"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"app": {
		{
			Language: "Erlang",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\{\\s*(?:application|'application')\\s*,\\s*(?:[a-z]+[\\w@]*|'[^']+')\\s*,\\s*\\[(?:.|[\\r\\n])*\\]\\s*\\}\\.[ \\t]*$"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"as": {
		{
			Language: "ActionScript",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(?:package(?:\\s+[\\w.]+)?\\s+(?:\\{|$)|import\\s+[\\w.*]+\\s*;|(?:intrinsic\\s+)class\\s+[\\w<>.]+|\\s+class\\s+extends\\s+[\\w<>.]+|(?:(?:public|protected|private|static)\\s+)*(?:(?:var|const|local)\\s+\\w+\\s*:\\s*[\\w<>.]+(?:\\s*=.*)?\\s*;|function\\s+\\w+\\s*\\((?:\\s*\\w+\\s*:\\s*[\\w<>.]+\\s*(,\\s*\\w+\\s*:\\s*[\\w<>.]+\\s*)*)?\\)))"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"asc": {
		{
			Language: "Public Key",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(----[- ]BEGIN|ssh-(rsa|dss)) "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "AsciiDoc",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[=-]+\\s|\\{\\{[A-Za-z]"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "AGS Script",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(\\/\\/.+|((import|export)\\s+)?(function|int|float|char)\\s+((room|repeatedly|on|game)_)?([A-Za-z]+[A-Za-z_0-9]+)\\s*[;\\(])"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"asm": {
		{
			Language: "Assembly",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)mov\\s+[^\\s]{2,},"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Motorola 68K Assembly",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?im)\\bmoveq(?:\\.l)?\\s+#(?:\\$-?[0-9a-f]{1,3}|%[0-1]{1,8}|-?[0-9]{1,3}),\\s*d[0-7]\\b"),
				regexp.MustCompile("(?im)^\\s*move(?:\\.[bwl])?\\s+(?:sr|usp),\\s*[^\\s]+"),
				regexp.MustCompile("(?im)^\\s*move\\.[bwl]\\s+.*\\b[ad]\\d"),
				regexp.MustCompile("(?im)^\\s*movem\\.[bwl]\\b"),
				regexp.MustCompile("(?im)^\\s*move[mp](?:\\.[wl])?\\b"),
				regexp.MustCompile("(?im)^\\s*btst\\b"),
				regexp.MustCompile("(?im)^\\s*dbra\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"asy": {
		{
			Language: "LTspice Symbol",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^SymbolType[ \\t]"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Asymptote",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"bas": {
		{
			Language: "B4X",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\A\\W{0,3}(?:.*(?:\\r?\\n|\\r)){0,9}B4(?:J|A|R|i)=true"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "FreeBASIC",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^[ \\t]*#(?:define|endif|endmacro|ifn?def|include|lang|macro|pragma)(?:$|\\s)"),
				regexp.MustCompile("(?i)^[ \\t]*dim( shared)? [a-z_][a-z0-9_]* as [a-z_][a-z0-9_]* ptr"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "FreeBASIC",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^[ \\t]*return "),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("(?i)[ \\t]*gosub "),
			},
		},
		{
			Language: "BASIC",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\A\\s*\\d"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "QuickBASIC",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[ ]*(CONST|DIM|REDIM|DEFINT|PRINT|DECLARE (SUB|FUNCTION)|FUNCTION|SUB) "),
				regexp.MustCompile("(#|$)lang:?\\s*\"?qb\"?"),
				regexp.MustCompile("(?i)'\\$INCLUDE:"),
				regexp.MustCompile("(?i)^[ ]*CLS[ ]*('|:|\\r|\\n)"),
				regexp.MustCompile("(?i)^[ ]*OPTION _EXPLICIT"),
				regexp.MustCompile("(?i)^[ ]*DIM SHARED "),
				regexp.MustCompile("(?i)^[ ]*PRINT \""),
				regexp.MustCompile("(?i) As _(Byte|Offset|MEM)"),
				regexp.MustCompile("(?i)^[ ]*_(DISPLAY|DEST|CONSOLE|SOURCE|FREEIMAGE|PALETTECOLOR|PRINTSTRING|LOADFONT|PUTIMAGE)"),
				regexp.MustCompile("(?i)^[ ]*_(TITLE|PLAYMOD) \""),
				regexp.MustCompile("(?i)^[ ]*_(LIMIT|SCREEN|DELAY) \\.?\\d+"),
				regexp.MustCompile("(?i)\\b_(MOUSEBUTTON|NEWIMAGE|KEYDOWN|WIDTH|HEIGHT)\\("),
				regexp.MustCompile("(?i)^[ ]*\\$(CONSOLE|CHECKING):"),
				regexp.MustCompile("(?i)^[ ]*\\$(FULLSCREEN|RESIZE|STATIC|DYNAMIC|NOPREFIX|SCREENSHOW|SCREENHIDE|EXEICON)\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "VBA",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\b(?:VBA|[vV]ba)(?:\\b|[0-9A-Z_])"),
				regexp.MustCompile("^[ ]*(?:Public|Private)? Declare PtrSafe (?:Sub|Function)\\b"),
				regexp.MustCompile("^[ ]*#If Win64\\b"),
				regexp.MustCompile("^[ ]*(?:Dim|Const) [0-9a-zA-Z_]*[ ]*As Long(?:Ptr|Long)\\b"),
				regexp.MustCompile("^[ ]*Option (?:Private Module|Compare Database)\\b"),
				regexp.MustCompile("(?: |\\()(?:Access|Excel|Outlook|PowerPoint|Visio|Word|VBIDE)\\.\\w"),
				regexp.MustCompile("\\b(?:(?:Active)?VBProjects?|VBComponents?|Application\\.(?:VBE|ScreenUpdating))\\b"),
				regexp.MustCompile("\\b(?:ThisDrawing|AcadObject|Active(?:Explorer|Inspector|Window\\.Presentation|Presentation|Document)|Selection\\.(?:Document|Find|Paragraphs|Range))\\b"),
				regexp.MustCompile("\\b(?:(?:This|Active)?Workbooks?|Worksheets?|Active(?:Sheet|Chart|Cell)|WorksheetFunction)\\b"),
				regexp.MustCompile("\\b(?:Range\\(\".*|Cells\\([0-9a-zA-Z_]*, (?:[0-9a-zA-Z_]*|\"[a-zA-Z]{1,3}\"))\\)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Visual Basic 6.0",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[ ]*Attribute VB_Name = "),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"bb": {
		{
			Language: "BlitzBasic",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(<^\\s*; |End Function)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "BitBake",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(# |include|require|inherit)\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Clojure",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\((def|defn|defmacro|let)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"bf": {
		{
			Language: "Beef",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?-m)^\\s*using\\s+(System|Beefy)(\\.(.*))?;\\s*$"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "HyPhy",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?-m)^\\s*#include\\s+\".*\";\\s*$"),
				regexp.MustCompile("\\sfprintf\\s*\\("),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Brainfuck",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(>\\+>|>\\+<)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"bi": {
		{
			Language: "FreeBASIC",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^[ \\t]*#(?:define|endif|endmacro|ifn?def|include|lang|macro|pragma)(?:$|\\s)"),
				regexp.MustCompile("(?i)^[ \\t]*dim( shared)? [a-z_][a-z0-9_]* as [a-z_][a-z0-9_]* ptr"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "FreeBASIC",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^[ \\t]*return "),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("(?i)[ \\t]*gosub "),
			},
		},
		{
			Language: "QuickBASIC",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[ ]*(CONST|DIM|REDIM|DEFINT|PRINT|DECLARE (SUB|FUNCTION)|FUNCTION|SUB) "),
				regexp.MustCompile("(#|$)lang:?\\s*\"?qb\"?"),
				regexp.MustCompile("(?i)'\\$INCLUDE:"),
				regexp.MustCompile("(?i)^[ ]*CLS[ ]*('|:|\\r|\\n)"),
				regexp.MustCompile("(?i)^[ ]*OPTION _EXPLICIT"),
				regexp.MustCompile("(?i)^[ ]*DIM SHARED "),
				regexp.MustCompile("(?i)^[ ]*PRINT \""),
				regexp.MustCompile("(?i) As _(Byte|Offset|MEM)"),
				regexp.MustCompile("(?i)^[ ]*_(DISPLAY|DEST|CONSOLE|SOURCE|FREEIMAGE|PALETTECOLOR|PRINTSTRING|LOADFONT|PUTIMAGE)"),
				regexp.MustCompile("(?i)^[ ]*_(TITLE|PLAYMOD) \""),
				regexp.MustCompile("(?i)^[ ]*_(LIMIT|SCREEN|DELAY) \\.?\\d+"),
				regexp.MustCompile("(?i)\\b_(MOUSEBUTTON|NEWIMAGE|KEYDOWN|WIDTH|HEIGHT)\\("),
				regexp.MustCompile("(?i)^[ ]*\\$(CONSOLE|CHECKING):"),
				regexp.MustCompile("(?i)^[ ]*\\$(FULLSCREEN|RESIZE|STATIC|DYNAMIC|NOPREFIX|SCREENSHOW|SCREENHIDE|EXEICON)\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"bs": {
		{
			Language: "Bikeshed",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(?i:<pre\\s+class)\\s*=\\s*('|\\\"|\\b)metadata\\b('|\\\"|\\b)[^>\\r\\n]*>"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "BrighterScript",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:^\\s*(?:sub\\s*\\w+\\(.*?\\))|(?::\\s*sub\\(.*?\\))$)"),
				regexp.MustCompile("(?i:^\\s*(end\\ssub)$)"),
				regexp.MustCompile("(?i:^\\s*(?:function\\s*\\w+\\(.*?\\)\\s*as\\s*\\w*)|(?::\\s*function\\(.*?\\)\\s*as\\s*\\w*)$)"),
				regexp.MustCompile("(?i:^\\s*(end\\sfunction)$)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Bluespec BH",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^package\\s+[A-Za-z_][A-Za-z0-9_']*(?:\\s*\\(|\\s+where)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"bst": {
		{
			Language: "BibTeX Style",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("ENTRY\\s*\\{"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "BuildStream",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"builds": {
		{
			Language: "XML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(\\s*)(?i:<Project|<Import|<Property|<?xml|xmlns)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"cairo": {
		{
			Language: "Cairo Zero",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(^(\\s*)%lang(\\s+)([A-Za-z0-9_]+))|(^(\\s*)%builtins(\\s+)([A-Za-z0-9_]+\\s*)*$)|(^(\\s*)from(\\s+)starkware\\.(cairo|starknet)\\.([A-Za-z0-9_.\\s]+?)import)|(,\\s*ap\\+\\+;$)|(;\\s*ap\\+\\+$)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Cairo",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"ch": {
		{
			Language: "xBase",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*#\\s*(?i:if|ifdef|ifndef|define|command|xcommand|translate|xtranslate|include|pragma|undef)\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"cl": {
		{
			Language: "Common Lisp",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*\\((?i:defun|in-package|defpackage) "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Cool",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^class"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "OpenCL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\/\\* |\\/\\/ |^\\}"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"cls": {
		{
			Language: "Visual Basic 6.0",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[ ]*VERSION [0-9]\\.[0-9] CLASS"),
				regexp.MustCompile("^\\s*BEGIN(?:\\r?\\n|\\r)\\s*MultiUse\\s*=.*(?:\\r?\\n|\\r)\\s*Persistable\\s*="),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "VBA",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[ ]*VERSION [0-9]\\.[0-9] CLASS"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "TeX",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*\\\\(?:NeedsTeXFormat|ProvidesClass)\\{"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "ObjectScript",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^Class\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "OpenEdge ABL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^\\s*(?:end\\s+(?:class|interface)\\.|(?:class|interface)\\s+[a-z_][a-z0-9_#$%&-]*:)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"cmp": {
		{
			Language: "Gerber Image",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[DGMT][0-9]{2}\\*(?:\\r?\\n|\\r)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"container": {
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[#\\s]*\\[[^\\]]+\\]\\s*$"),
				regexp.MustCompile("^[^#!;][^=]*="),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^[^#;=\\[]+[^ \\r\\n=]$"),
			},
		},
	},
	"cs": {
		{
			Language: "Smalltalk",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("![\\w\\s]+methodsFor: "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "C#",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(using\\s+[A-Z][\\s\\w.]+;|namespace\\s*[\\w\\.]+\\s*(\\{|;)|\\/\\/)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"csc": {
		{
			Language: "GSC",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*#\\s*(?:using|insert|include|define|namespace)[ \\t]+\\w"),
				regexp.MustCompile("^\\s*((?:autoexec|private)\\s+){0,2}function\\s+((?:autoexec|private)\\s+){0,2}\\w+\\s*\\("),
				regexp.MustCompile("\\b(?:level|self)[ \\t]+thread[ \\t]+(?:\\[\\[[ \\t]*(\\w+\\.)+[ \\t]*\\]\\]|\\w+)[ \\t]*\\([^\\r\\n\\)]*\\)[ \\t]*;"),
				regexp.MustCompile("^[ \\t]*#[ \\t]*(?:precache|using_animtree)[ \\t]*\\("),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"csl": {
		{
			Language: "XML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:^\\s*(<\\?xml|xmlns))"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Kusto",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(^\\|\\s*(where|extend|project|limit|summarize))|(^\\.\\w+)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"d": {
		{
			Language: "D",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^module\\s+[\\w.]*\\s*;|import\\s+[\\w\\s,.:]*;|\\w+\\s+\\w+\\s*\\(.*\\)(?:\\(.*\\))?\\s*\\{[^}]*\\}|unittest\\s*(?:\\(.*\\))?\\s*\\{[^}]*\\}"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "DTrace",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(\\w+:\\w*:\\w*:\\w*|BEGIN|END|provider\\s+|(tick|profile)-\\w+\\s+\\{[^}]*\\}|#pragma\\s+D\\s+(option|attributes|depends_on)\\s|#pragma\\s+ident\\s)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Makefile",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("([\\/\\\\].*:\\s+.*\\s\\\\$|: \\\\$|^[ %]:|^[\\w\\s\\/\\\\.]+\\w+\\.\\w+\\s*:\\s+[\\w\\s\\/\\\\.]+\\w+\\.\\w+)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"dsp": {
		{
			Language: "Microsoft Developer Studio Project",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("# Microsoft Developer Studio Generated Build File"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Faust",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\bprocess\\s*[(=]|\\b(library|import)\\s*\\(\\s*\"|\\bdeclare\\s+(name|version|author|copyright|license)\\s+\""),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"e": {
		{
			Language: "E",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(def|var)\\s+(.+):="),
				regexp.MustCompile("^\\s*(def|to)\\s+(\\w+)(\\(.+\\))?\\s+\\{"),
				regexp.MustCompile("^\\s*(when)\\s+(\\(.+\\))\\s+->\\s+\\{"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Eiffel",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*\\w+\\s*(?:,\\s*\\w+)*[:]\\s*\\w+\\s"),
				regexp.MustCompile("^\\s*\\w+\\s*(?:\\(\\s*\\w+[:][^)]+\\))?(?:[:]\\s*\\w+)?(?:--.+\\s+)*\\s+(?:do|local)\\s"),
				regexp.MustCompile("^\\s*(?:across|deferred|elseif|ensure|feature|from|inherit|inspect|invariant|note|once|require|undefine|variant|when)\\s*$"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Euphoria",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*namespace\\s"),
				regexp.MustCompile("^\\s*(?:public\\s+)?include\\s"),
				regexp.MustCompile("^\\s*(?:(?:public|export|global)\\s+)?(?:atom|constant|enum|function|integer|object|procedure|sequence|type)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"ecl": {
		{
			Language: "ECLiPSe",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[^#]+:-"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "ECL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile(":="),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"es": {
		{
			Language: "Erlang",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(?:%%|main\\s*\\(.*?\\)\\s*->)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "JavaScript",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\/\\/|[\"']use strict[\"']|export\\s+default\\s|\\/\\*(?:.|[\\r\\n])*?\\*\\/"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"ex": {
		{
			Language: "Elixir",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*@moduledoc\\s"),
				regexp.MustCompile("^\\s*(?:cond|import|quote|unless)\\s"),
				regexp.MustCompile("^\\s*def(?:exception|impl|macro|module|protocol)[(\\s]"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Euphoria",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*namespace\\s"),
				regexp.MustCompile("^\\s*(?:public\\s+)?include\\s"),
				regexp.MustCompile("^\\s*(?:(?:public|export|global)\\s+)?(?:atom|constant|enum|function|integer|object|procedure|sequence|type)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"f": {
		{
			Language: "Forth",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^: "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Filebench WML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("flowop"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Fortran",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(?i:[c*][^abd-z]|      (subroutine|program|end|data)\\s|\\s*!)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"for": {
		{
			Language: "Forth",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^: "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Fortran",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(?i:[c*][^abd-z]|      (subroutine|program|end|data)\\s|\\s*!)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"fr": {
		{
			Language: "Forth",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(: |also |new-device|previous )"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Frege",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(import|module|package|data|type) "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"frm": {
		{
			Language: "VBA",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[ ]*VERSION [0-9]\\.[0-9]{2}"),
				regexp.MustCompile("^\\s*Begin\\s+\\{[0-9A-Z\\-]*\\}\\s?"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Visual Basic 6.0",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[ ]*VERSION [0-9]\\.[0-9]{2}"),
				regexp.MustCompile("^\\s*Begin\\s+VB\\.Form\\s+"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\ATYPE=VIEW"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"fs": {
		{
			Language: "Forth",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(: |new-device)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "F#",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(#light|import|let|module|namespace|open|type)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "GLSL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(#version|precision|uniform|varying|vec[234])"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Filterscript",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("#include|#pragma\\s+(rs|version)|__attribute__"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"ftl": {
		{
			Language: "FreeMarker",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(?:<|[a-zA-Z-][a-zA-Z0-9_-]+[ \\t]+\\w)|\\$\\{\\w+[^\\r\\n]*?\\}|^[ \\t]*(?:<#--.*?-->|<#(?:[a-z]+)\\s[^>]*>.*?</#(?:[a-z]+)>|\\[#--.*?--\\]|\\[#(?:[a-z]+)\\s[^\\]]*\\].*?\\[#(?:[a-z]+)\\])"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Fluent",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^-?[a-zA-Z][a-zA-Z0-9_-]* *=|\\{\\$-?[a-zA-Z][-\\w]*(?:\\.[a-zA-Z][-\\w]*)?\\}"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"g": {
		{
			Language: "GAP",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\s*(Declare|BindGlobal|KeyDependentOperation|Install(Method|GlobalFunction)|SetPackageInfo)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "G-code",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[MG][0-9]+(?:\\r?\\n|\\r)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"gd": {
		{
			Language: "GAP",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\s*(Declare|BindGlobal|KeyDependentOperation)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "GDScript",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\s*(extends|var|const|enum|func|class|signal|tool|yield|assert|onready)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"gml": {
		{
			Language: "XML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:^\\s*(<\\?xml|xmlns))"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Graph Modeling Language",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:^\\s*(graph|node)\\s+\\[$)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Gerber Image",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[DGMT][0-9]{2}\\*$"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Game Maker Language",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"gs": {
		{
			Language: "GLSL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^#version\\s+[0-9]+\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Gosu",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^uses (java|gw)\\."),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Genie",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\[indent=[0-9]+\\]"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"gsc": {
		{
			Language: "GSC",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*#\\s*(?:using|insert|include|define|namespace)[ \\t]+\\w"),
				regexp.MustCompile("^\\s*((?:autoexec|private)\\s+){0,2}function\\s+((?:autoexec|private)\\s+){0,2}\\w+\\s*\\("),
				regexp.MustCompile("\\b(?:level|self)[ \\t]+thread[ \\t]+(?:\\[\\[[ \\t]*(\\w+\\.)+[ \\t]*\\]\\]|\\w+)[ \\t]*\\([^\\r\\n\\)]*\\)[ \\t]*;"),
				regexp.MustCompile("^[ \\t]*#[ \\t]*(?:precache|using_animtree)[ \\t]*\\("),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"gsh": {
		{
			Language: "GSC",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*#\\s*(?:using|insert|include|define|namespace)[ \\t]+\\w"),
				regexp.MustCompile("^\\s*((?:autoexec|private)\\s+){0,2}function\\s+((?:autoexec|private)\\s+){0,2}\\w+\\s*\\("),
				regexp.MustCompile("\\b(?:level|self)[ \\t]+thread[ \\t]+(?:\\[\\[[ \\t]*(\\w+\\.)+[ \\t]*\\]\\]|\\w+)[ \\t]*\\([^\\r\\n\\)]*\\)[ \\t]*;"),
				regexp.MustCompile("^[ \\t]*#[ \\t]*(?:precache|using_animtree)[ \\t]*\\("),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"gts": {
		{
			Language: "Gerber Image",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^G0."),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Glimmer TS",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^G0."),
			},
		},
	},
	"h": {
		{
			Language: "Objective-C",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(@(interface|class|protocol|property|end|synchronised|selector|implementation)\\b|#import\\s+.+\\.h[\">])"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "C++",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*#\\s*include <(cstdint|string|vector|map|list|array|bitset|queue|stack|forward_list|unordered_map|unordered_set|(i|o|io)stream)>"),
				regexp.MustCompile("^\\s*template\\s*<"),
				regexp.MustCompile("^[ \\t]*(try|constexpr)"),
				regexp.MustCompile("^[ \\t]*catch\\s*\\("),
				regexp.MustCompile("^[ \\t]*(class|(using[ \\t]+)?namespace)\\s+\\w+"),
				regexp.MustCompile("^[ \\t]*(private|public|protected):$"),
				regexp.MustCompile("__has_cpp_attribute|__cplusplus >"),
				regexp.MustCompile("std::\\w+"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "C",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"hh": {
		{
			Language: "Hack",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("<\\?hh"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"html": {
		{
			Language: "Ecmarkup",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("<emu-(?:alg|annex|biblio|clause|eqn|example|figure|gann|gmod|gprose|grammar|intro|not-ref|note|nt|prodref|production|rhs|table|t|xref)(?:$|\\s|>)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "HTML",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"i": {
		{
			Language: "Motorola 68K Assembly",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?im)\\bmoveq(?:\\.l)?\\s+#(?:\\$-?[0-9a-f]{1,3}|%[0-1]{1,8}|-?[0-9]{1,3}),\\s*d[0-7]\\b"),
				regexp.MustCompile("(?im)^\\s*move(?:\\.[bwl])?\\s+(?:sr|usp),\\s*[^\\s]+"),
				regexp.MustCompile("(?im)^\\s*move\\.[bwl]\\s+.*\\b[ad]\\d"),
				regexp.MustCompile("(?im)^\\s*movem\\.[bwl]\\b"),
				regexp.MustCompile("(?im)^\\s*move[mp](?:\\.[wl])?\\b"),
				regexp.MustCompile("(?im)^\\s*btst\\b"),
				regexp.MustCompile("(?im)^\\s*dbra\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "SWIG",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[ \\t]*%[a-z_]+\\b|^%[{}]$"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Assembly",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)mov\\s+[^\\s]+,"),
				regexp.MustCompile("^\\s+(i?)db\\s+[a-z\\d]"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"ice": {
		{
			Language: "JSON",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\A\\s*[{\\[]"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Slice",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"inc": {
		{
			Language: "Motorola 68K Assembly",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?im)\\bmoveq(?:\\.l)?\\s+#(?:\\$-?[0-9a-f]{1,3}|%[0-1]{1,8}|-?[0-9]{1,3}),\\s*d[0-7]\\b"),
				regexp.MustCompile("(?im)^\\s*move(?:\\.[bwl])?\\s+(?:sr|usp),\\s*[^\\s]+"),
				regexp.MustCompile("(?im)^\\s*move\\.[bwl]\\s+.*\\b[ad]\\d"),
				regexp.MustCompile("(?im)^\\s*movem\\.[bwl]\\b"),
				regexp.MustCompile("(?im)^\\s*move[mp](?:\\.[wl])?\\b"),
				regexp.MustCompile("(?im)^\\s*btst\\b"),
				regexp.MustCompile("(?im)^\\s*dbra\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "PHP",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^<\\?(?:php)?"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "SourcePawn",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^public\\s+(?:SharedPlugin(?:\\s+|:)__pl_\\w+\\s*=(?:\\s*\\{)?|(?:void\\s+)?__pl_\\w+_SetNTVOptional\\(\\)(?:\\s*\\{)?)"),
				regexp.MustCompile("^methodmap\\s+\\w+\\s+<\\s+\\w+"),
				regexp.MustCompile("^\\s*MarkNativeAsOptional\\s*\\("),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "NASL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*include\\s*\\(\\s*(?:\"|')[\\\\/\\w\\-\\.:\\s]+\\.(?:nasl|inc)\\s*(?:\"|')\\s*\\)\\s*;"),
				regexp.MustCompile("^\\s*(?:global|local)_var\\s+(?:\\w+(?:\\s*=\\s*[\\w\\-\"']+)?\\s*)(?:,\\s*\\w+(?:\\s*=\\s*[\\w\\-\"']+)?\\s*)*\\s*;"),
				regexp.MustCompile("^\\s*namespace\\s+\\w+\\s*\\{"),
				regexp.MustCompile("^\\s*object\\s+\\w+\\s*(?:extends\\s+\\w+(?:::\\w+)?)?\\s*\\{"),
				regexp.MustCompile("^\\s*(?:public\\s+|private\\s+|\\s*)function\\s+\\w+\\s*\\([\\w\\s,]*\\)\\s*\\{"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "POV-Ray SDL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*#(declare|local|macro|while)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Pascal",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:^\\s*\\{\\$(?:mode|ifdef|undef|define)[ ]+[a-z0-9_]+\\})"),
				regexp.MustCompile("^\\s*end[.;]\\s*$"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "BitBake",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^inherit(\\s+[\\w.-]+)+\\s*$"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Assembly",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(?i)[^\"m]*mov\\s+[^\\s]+,"),
				regexp.MustCompile("^\\s+(?i)db\\s+[a-z\\d]"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"json": {
		{
			Language: "OASv2-json",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\"swagger\":\\s?\"2.[0-9.]+\""),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "OASv3-json",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\"openapi\":\\s?\"3.[0-9.]+\""),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "JSON",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"k": {
		{
			Language: "KCL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^schema [A-Za-z0-9_-]+"),
				regexp.MustCompile("^\\}$"),
				regexp.MustCompile("\\s*\\}\\s*"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "KFramework",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^requires\\s+\"[^\"]+\"$"),
				regexp.MustCompile("^syntax\\s+\\w+\\s+::=.*"),
				regexp.MustCompile("^endmodule$"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"l": {
		{
			Language: "Common Lisp",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\(def(un|macro)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Lex",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(%[%{}]xs|<.*>)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\.[A-Za-z]{2}(\\s|$)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "PicoLisp",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\((de|class|rel|code|data|must)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"lean": {
		{
			Language: "Lean",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^import [a-z]"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Lean 4",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^import [A-Z]"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"lisp": {
		{
			Language: "Common Lisp",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*\\((?i:defun|in-package|defpackage) "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "NewLisp",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*\\(define "),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"lp": {
		{
			Language: "Lambdapi",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(?:opaque\\s+symbol|symbol|rule|notation|constant|injective|require(?:\\s+open)?|open|type|assert(?:not)?|compute)\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Linear Programming",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^\\s*(?:minimize|minimum|min|maximize|maximum|max)(?:\\s+multi-objectives)?\\s*$"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Answer Set Programming",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*#(?:include|const|program|script|show|minimize|maximize|heuristic|project|edge|theory|defined)\\b"),
				regexp.MustCompile("^\\s*(?:[A-Za-z_]\\w*(?:\\([^)]*\\))?\\s*:-|:-)\\s[^.]*\\."),
				regexp.MustCompile("^\\s*[a-z_][a-zA-Z0-9_]*(?:\\([^)]*\\))?\\s*\\.\\s*$"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"ls": {
		{
			Language: "LoomScript",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*package\\s*[\\w\\.\\/\\*\\s]*\\s*\\{"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "LiveScript",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"lsp": {
		{
			Language: "Common Lisp",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*\\((?i:defun|in-package|defpackage) "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "NewLisp",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*\\(define "),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"m": {
		{
			Language: "Objective-C",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(@(interface|class|protocol|property|end|synchronised|selector|implementation)\\b|#import\\s+.+\\.h[\">])"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Mercury",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile(":- module"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "MUF",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^: "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "M",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*;"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Wolfram Language",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\(\\*"),
				regexp.MustCompile("\\*\\)$"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "MATLAB",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*%"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Limbo",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\w+\\s*:\\s*module\\s*\\{"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"m4": {
		{
			Language: "M4Sugar",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("AC_DEFUN|AC_PREREQ|AC_INIT"),
				regexp.MustCompile("^_?m4_"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "M4",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"man": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"mask": {
		{
			Language: "Unity3D Asset",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("tag:unity3d.com"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"mc": {
		{
			Language: "Win32 Message File",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^[ \\t]*(\\/\\*\\s*)?MessageId=|^\\.$"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "M4",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^dnl|^divert\\((?:-?\\d+)?\\)|^\\w+\\(`[^\\r\\n]*?'[),]"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Monkey C",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\b(?:using|module|function|class|var)\\s+\\w"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"md": {
		{
			Language: "Markdown",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(^[-A-Za-z0-9=#!\\*\\[|>])|<\\/"),
				regexp.MustCompile("\\A\\z"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "GCC Machine Description",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(;;|\\(define_)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"mdoc": {
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*Dd +(?:[^\"\\s]+|\"[^\"]+\")"),
				regexp.MustCompile("^[.'][ \\t]*Dt +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*Sh +(?:[^\"\\s]|\"[^\"]+\")"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff Manpage",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][ \\t]*TH +(?:[^\"\\s]+|\"[^\"]+\") +\"?(?:[1-9]|@[^\\s@]+@)"),
				regexp.MustCompile("^[.'][ \\t]*SH +(?:[^\"\\s]+|\"[^\"\\s]+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"ml": {
		{
			Language: "OCaml",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(^\\s*module)|let rec |match\\s+(\\S+\\s)+with"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Standard ML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("=> |case\\s+(\\S+\\s)+of"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"mod": {
		{
			Language: "XML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("<!ENTITY "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "NMODL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\b(NEURON|INITIAL|UNITS)\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Modula-2",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(?i:MODULE|END) [\\w\\.]+;"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Linux Kernel Module",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"mojo": {
		{
			Language: "Mojo",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(alias|def|from|fn|import|struct|trait)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "XML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*<\\?xml"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"mount": {
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[#\\s]*\\[[^\\]]+\\]\\s*$"),
				regexp.MustCompile("^[^#!;][^=]*="),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^[^#;=\\[]+[^ \\r\\n=]$"),
			},
		},
	},
	"mps": {
		{
			Language: "JetBrains MPS",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("<persistence"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Mathematical Programming System",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^\\s*(ROWS|COLUMNS)\\s*$"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"ms": {
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.'][A-Za-z]{2}(\\s|$)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Unix Assembly",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*\\.(?:include\\s|globa?l\\s|[A-Za-z][_A-Za-z0-9]*:)"),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("/\\*"),
			},
		},
		{
			Language: "MAXScript",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"msg": {
		{
			Language: "OMNeT++ MSG",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^cplusplus\\(?[\\S]*\\)?[\\s]*\\{?\\{?|^namespace[\\s]+([^.\\s]*\\.)*[^.\\s]*;|^struct[\\s]+[\\S]+|^message[\\s]+[\\S]+(extends )?[\\S]*[\\s]*|^packet[\\s]+[\\S]+|^class[\\s]+[\\S]+(extends )?[\\S]*[\\s]*|^enum[\\s]+[\\S]+|^import ([^.\\s]*\\.)*[^.\\s]*;"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "ROS Interface",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^[a-z]\\w*(?:\\/[a-z]\\w*)?(?:<=\\d+)?(?:\\[(?:<=\\d+)?\\])?\\s+\\w+\\b"),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^\\s*[^\\s@#\\w-]"),
			},
		},
	},
	"n": {
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[.']"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Nemerle",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(module|namespace|using)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"ncl": {
		{
			Language: "XML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*<\\?xml\\s+version"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Gerber Image",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[DGMT][0-9]{2}\\*(?:\\r?\\n|\\r)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Nickel",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^let(?:\\srec)?(?:\\s[a-zA-Z_][a-zA-Z0-9_]*)?"),
				regexp.MustCompile("^import\\s\"[^\"]+\"\\s+as\\s"),
				regexp.MustCompile("std\\.[a-zA-Z_][a-zA-Z0-9_]*\\."),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("THE_TITLE"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "NCL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^load \""),
				regexp.MustCompile("^begin$"),
				regexp.MustCompile("[0-9]\\.$"),
				regexp.MustCompile("^;"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"network": {
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[#\\s]*\\[[^\\]]+\\]\\s*$"),
				regexp.MustCompile("^[^#!;][^=]*="),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^[^#;=\\[]+[^ \\r\\n=]$"),
			},
		},
	},
	"nl": {
		{
			Language: "NL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(b|g)[0-9]+ "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "NewLisp",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"nr": {
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\."),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Noir",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"nu": {
		{
			Language: "Nushell",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(import|export|module|def|let|let-env) "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Nu",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"odin": {
		{
			Language: "Object Data Instance Notation",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?:^|<)\\s*[A-Za-z0-9_]+\\s*=\\s*<"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Odin",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("package\\s+\\w+|\\b(?:im|ex)port\\s*\"[\\w:./]+\"|\\w+\\s*::\\s*(?:proc|struct)\\s*\\(|^\\s*//\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"p": {
		{
			Language: "Gnuplot",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^s?plot\\b"),
				regexp.MustCompile("^set\\s+(term|terminal|out|output|[xy]tics|[xy]label|[xy]range|style)\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "OpenEdge ABL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)\\bDEFINE\\s+(?:VARIABLE|TEMP-TABLE|BUFFER|QUERY|INPUT\\s+PARAMETER|OUTPUT\\s+PARAMETER)\\b"),
				regexp.MustCompile("(?i)\\bEND(?:\\s+(?:PROCEDURE|FUNCTION|DO|FOR\\s+EACH))?\\."),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"pc": {
		{
			Language: "Pro*C",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*EXEC\\s+SQL\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "pkg-config",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^Name:[ \\t]+\\S"),
				regexp.MustCompile("^Description:[ \\t]+\\S"),
				regexp.MustCompile("^Version:[ \\t]+\\S"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"php": {
		{
			Language: "Hack",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("<\\?hh"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "PHP",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("<\\?[^h]"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"pkl": {
		{
			Language: "Pkl",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(module|import|amends|extends|local|const|fixed|abstract|open|class|typealias|@\\w+)\\b"),
				regexp.MustCompile("^\\s*[a-zA-Z0-9_$]+\\s*(=|{|:)|^\\s*`[^`]+`\\s*(=|{|:)|for\\s*\\(|when\\s*\\("),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Pickle",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"pl": {
		{
			Language: "Prolog",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[^#]*:-"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Perl",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\buse\\s+(?:strict\\b|v?5\\b)"),
				regexp.MustCompile("^\\s*use\\s+(?:constant|overload)\\b"),
				regexp.MustCompile("^\\s*(?:\\*|(?:our\\s*)?@)EXPORT\\s*="),
				regexp.MustCompile("^\\s*package\\s+[^\\W\\d]\\w*(?:::\\w+)*\\s*(?:[;{]|\\sv?\\d)"),
				regexp.MustCompile("[\\s$][^\\W\\d]\\w*(?::\\w+)*->[a-zA-Z_\\[({]"),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^\\s*use\\s+v6\\b"),
			},
		},
		{
			Language: "Raku",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(?:use\\s+v6\\b|\\bmodule\\b|\\b(?:my\\s+)?class\\b)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"plist": {
		{
			Language: "XML Property List",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(?:<\\?xml\\s|<!DOCTYPE\\s+plist|<plist(?:\\s+version\\s*=\\s*[\"']\\d+(?:\\.\\d+)?[\"'])?\\s*>\\s*$)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "OpenStep Property List",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"plt": {
		{
			Language: "Prolog",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*:-"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"pm": {
		{
			Language: "Perl",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\buse\\s+(?:strict\\b|v?5\\b)"),
				regexp.MustCompile("^\\s*use\\s+(?:constant|overload)\\b"),
				regexp.MustCompile("^\\s*(?:\\*|(?:our\\s*)?@)EXPORT\\s*="),
				regexp.MustCompile("^\\s*package\\s+[^\\W\\d]\\w*(?:::\\w+)*\\s*(?:[;{]|\\sv?\\d)"),
				regexp.MustCompile("[\\s$][^\\W\\d]\\w*(?::\\w+)*->[a-zA-Z_\\[({]"),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^\\s*use\\s+v6\\b"),
			},
		},
		{
			Language: "Raku",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(?:use\\s+v6\\b|\\bmodule\\b|\\b(?:my\\s+)?class\\b)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "X PixMap",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*\\/\\* XPM \\*\\/"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"pod": {
		{
			Language: "Pod 6",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[\\s&&[^\\r\\n]]*=(comment|begin pod|begin para|item\\d+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Pod",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"pp": {
		{
			Language: "Pascal",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*end[.;]"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Puppet",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s+\\w+\\s+=>\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"pro": {
		{
			Language: "Proguard",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^-(include\\b.*\\.pro$|keep\\b|keepclassmembers\\b|keepattributes\\b)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Prolog",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[^\\[#]+:-"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("last_client="),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "QMake",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("HEADERS"),
				regexp.MustCompile("SOURCES"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "IDL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(?i:function|pro|compile_opt) \\w[ \\w,:]*$"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"properties": {
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[^#!;][^=]*="),
				regexp.MustCompile("^[;\\[]"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Java Properties",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[^#!;][^=]*="),
				regexp.MustCompile("^[#!]"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[^#!;][^=]*="),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Java Properties",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[^#!][^:]*:"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"q": {
		{
			Language: "q",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("((?i:[A-Z.][\\w.]*:\\{)|^\\\\(cd?|d|l|p|ts?) )"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "HiveQL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:SELECT\\s+[\\w*,]+\\s+FROM|(CREATE|ALTER|DROP)\\s(DATABASE|SCHEMA|TABLE))"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"qs": {
		{
			Language: "Q#",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^((\\/{2,3})?\\s*(namespace|operation)\\b)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Qt Script",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(\\w+\\.prototype\\.\\w+|===|\\bvar\\b)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"r": {
		{
			Language: "Rebol",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:\\bRebol\\b)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Rez",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(#include\\s+[\"<](Types\\.r|Carbon\\/Carbon\\.r)[\">])|((resource|data|type)\\s+'[A-Za-z0-9]{4}'\\s+((\\(.*\\)\\s+){0,1}){)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "R",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("<-|^\\s*#"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"re": {
		{
			Language: "Reason",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*module\\s+type\\s"),
				regexp.MustCompile("^\\s*(?:include|open)\\s+\\w+\\s*;\\s*$"),
				regexp.MustCompile("^\\s*let\\s+(?:module\\s\\w+\\s*=\\s*\\{|\\w+:\\s+.*=.*;\\s*$)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "C++",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*#(?:(?:if|ifdef|define|pragma)\\s+\\w|\\s*include\\s+<[^>]+>)"),
				regexp.MustCompile("^\\s*template\\s*<"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"res": {
		{
			Language: "ReScript",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(let|module|type)\\s+\\w*\\s+=\\s+"),
				regexp.MustCompile("^\\s*(?:include|open)\\s+\\w+\\s*$"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"resource": {
		{
			Language: "RobotFramework",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\*{3} (Settings|Variables|Keywords) \\*{3}$"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"rno": {
		{
			Language: "RUNOFF",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:^\\.!|^\\f|\\f$|^\\.end lit(?:eral)?\\b|^\\.[a-zA-Z].*?;\\.[a-zA-Z](?:[; \\t])|\\^\\*[^\\s*][^*]*\\\\\\*(?:$|\\s)|^\\.c;[ \\t]*\\w+)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Roff",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\.\\\\\" "),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"rpy": {
		{
			Language: "Python",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(import|from|class|def)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Ren'Py",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"rs": {
		{
			Language: "Rust",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(use |fn |mod |pub |macro_rules|impl|#!?\\[)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "RenderScript",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("#include|#pragma\\s+(rs|version)|__attribute__"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "XML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*<\\?xml"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"s": {
		{
			Language: "Unix Assembly",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:mov[lq]?)\\s+[%\\$]"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Assembly",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:mov)\\s+[^\\s%]{2,},"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Motorola 68K Assembly",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?im)\\bmoveq(?:\\.l)?\\s+#(?:\\$-?[0-9a-f]{1,3}|%[0-1]{1,8}|-?[0-9]{1,3}),\\s*d[0-7]\\b"),
				regexp.MustCompile("(?im)^\\s*move(?:\\.[bwl])?\\s+(?:sr|usp),\\s*[^\\s]+"),
				regexp.MustCompile("(?im)^\\s*move\\.[bwl]\\s+.*\\b[ad]\\d"),
				regexp.MustCompile("(?im)^\\s*movem\\.[bwl]\\b"),
				regexp.MustCompile("(?im)^\\s*move[mp](?:\\.[wl])?\\b"),
				regexp.MustCompile("(?im)^\\s*btst\\b"),
				regexp.MustCompile("(?im)^\\s*dbra\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"sc": {
		{
			Language: "SuperCollider",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:\\^(this|super)\\.|^\\s*~\\w+\\s*=\\.)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Scala",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(^\\s*import (scala|java)\\.|^\\s*class\\b)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"scd": {
		{
			Language: "SuperCollider",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:\\^(this|super)\\.|^\\s*(~\\w+\\s*=\\.|SynthDef\\b))"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Markdown",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^#+\\s+(NAME|SYNOPSIS|DESCRIPTION)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"scm": {
		{
			Language: "Tree-sitter Query",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\(#[\\w-]+[!\\?]"),
				regexp.MustCompile("(?:[\\)\\]]\\s*[\\*\\+\\?](?:\\s|$))"),
				regexp.MustCompile("(?:^\\s*\\w+:\\s*[\\(\\[\\\"])"),
				regexp.MustCompile("\\(#(?:set!|(?:not-)?(?:any-of|match)\\?)"),
				regexp.MustCompile("@[\\w.-]+(?:\\)\\s|$)"),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("\\([+\\-:<>\\/=~\\)]"),
			},
		},
		{
			Language: "Scheme",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?:'[\\(\\*#]|\\w->\\w|\\.\\.\\.[\\s\\)]|\\([+\\-:<>\\/=~\\)]|~>|[#`]\\(|#:\\w)"),
				regexp.MustCompile("^\\s*\\((?:define\\*?|import|library|lambda)"),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("\\(#[\\w-]+[!\\?]"),
				regexp.MustCompile("(?:[\\)\\]]\\s*[\\*\\+\\?](?:\\s|$))"),
				regexp.MustCompile("@[\\w.-]+(?:\\)\\s|$)"),
			},
		},
	},
	"service": {
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[#\\s]*\\[[^\\]]+\\]\\s*$"),
				regexp.MustCompile("^[^#!;][^=]*="),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^[^#;=\\[]+[^ \\r\\n=]$"),
			},
		},
	},
	"socket": {
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[#\\s]*\\[[^\\]]+\\]\\s*$"),
				regexp.MustCompile("^[^#!;][^=]*="),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^[^#;=\\[]+[^ \\r\\n=]$"),
			},
		},
	},
	"sol": {
		{
			Language: "Solidity",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\bpragma\\s+solidity\\b|\\b(?:abstract\\s+)?contract\\s+[a-zA-Z$_][a-zA-Z0-9$_]*(?:\\s+is\\s+(?:[a-zA-Z0-9$_][^\\{]*?)?)?\\s*\\{"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Gerber Image",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[DGMT][0-9]{2}\\*(?:\\r?\\n|\\r)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"sql": {
		{
			Language: "PLpgSQL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:^\\\\i\\b|AS\\s+\\$\\$|LANGUAGE\\s+'?plpgsql'?|BEGIN(\\s+WORK)?\\s*;)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "SQLPL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:ALTER\\s+MODULE|MODE\\s+DB2SQL|\\bSYS(CAT|PROC)\\.|ASSOCIATE\\s+RESULT\\s+SET|\\bEND!\\s*$)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "PLSQL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:\\$\\$PLSQL_|XMLTYPE|systimestamp|\\.nextval|CONNECT\\s+BY|AUTHID\\s+(DEFINER|CURRENT_USER)|constructor\\W+function)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "TSQL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:^\\s*GO\\b|BEGIN(\\s+TRY|\\s+CATCH)|OUTPUT\\s+INSERTED|DECLARE\\s+@|\\[dbo\\])"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "SQL",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"srt": {
		{
			Language: "SubRip Text",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(\\d{2}:\\d{2}:\\d{2},\\d{3})\\s*(-->)\\s*(\\d{2}:\\d{2}:\\d{2},\\d{3})$"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"srv": {
		{
			Language: "ROS Interface",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i)^[a-z]\\w*(?:\\/[a-z]\\w*)?(?:<=\\d+)?(?:\\[(?:<=\\d+)?\\])?\\s+\\w+\\b"),
				regexp.MustCompile("^---\\s*$"),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^\\s*[^\\s@#\\w-]"),
			},
		},
	},
	"st": {
		{
			Language: "StringTemplate",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\$\\w+[($]|.!\\s*.+?\\s*!.|<!\\s*.+?\\s*!>|\\[!\\s*.+?\\s*!\\]|\\{!\\s*.+?\\s*!\\}"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Smalltalk",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\A\\s*[\\[{(^\"'\\w#]|[a-zA-Z_]\\w*\\s*:=\\s*[a-zA-Z_]\\w*|class\\s*>>\\s*[a-zA-Z_]\\w*|^[a-zA-Z_]\\w*\\s+[a-zA-Z_]\\w*:|^Class\\s*\\{|if(?:True|False):\\s*\\["),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"star": {
		{
			Language: "STAR",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^loop_\\s*$"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Starlark",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"stl": {
		{
			Language: "STL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\A\\s*solid(?:$|\\s)[\\s\\S]*^endsolid(?:$|\\s)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"svx": {
		{
			Language: "Survex data",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\A(;|\\*[^*]+$)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "mdsvex",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"sw": {
		{
			Language: "Sway",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(?:(?:abi|dep|fn|impl|mod|pub|trait)\\s|#\\[)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "XML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*<\\?xml\\s+version"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"t": {
		{
			Language: "Perl",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\buse\\s+(?:strict\\b|v?5\\b)"),
				regexp.MustCompile("^\\s*use\\s+(?:constant|overload)\\b"),
				regexp.MustCompile("^\\s*(?:\\*|(?:our\\s*)?@)EXPORT\\s*="),
				regexp.MustCompile("^\\s*package\\s+[^\\W\\d]\\w*(?:::\\w+)*\\s*(?:[;{]|\\sv?\\d)"),
				regexp.MustCompile("[\\s$][^\\W\\d]\\w*(?::\\w+)*->[a-zA-Z_\\[({]"),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^\\s*use\\s+v6\\b"),
			},
		},
		{
			Language: "Raku",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*(?:use\\s+v6\\b|\\bmodule\\b|\\bmy\\s+class\\b)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Turing",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\s*%[ \\t]+|^\\s*var\\s+\\w+(\\s*:\\s*\\w+)?\\s*:=\\s*\\w+"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"tact": {
		{
			Language: "JSON",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\A\\s*\\{\\\""),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Tact",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"tag": {
		{
			Language: "Java Server Pages",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("<%[@!=\\s]?\\s*(taglib|tag|include|attribute|variable)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"target": {
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[#\\s]*\\[[^\\]]+\\]\\s*$"),
				regexp.MustCompile("^[^#!;][^=]*="),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^[^#;=\\[]+[^ \\r\\n=]$"),
			},
		},
	},
	"timer": {
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[#\\s]*\\[[^\\]]+\\]\\s*$"),
				regexp.MustCompile("^[^#!;][^=]*="),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("^[^#;=\\[]+[^ \\r\\n=]$"),
			},
		},
	},
	"tl": {
		{
			Language: "Teal",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("--.*"),
				regexp.MustCompile("\\b(local|function|end|record|interface|enum)\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Type Language",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"tlv": {
		{
			Language: "TL-Verilog",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\\\.{0,10}TLV_version"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"toc": {
		{
			Language: "World of Warcraft Addon Data",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^## |@no-lib-strip@"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "TeX",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\\\(contentsline|defcounter|beamer|boolfalse)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"tpl": {
		{
			Language: "Go Template",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\{\\{-?\\s*(\\`?\\\"\\\\?\\\"?|\\/\\*\\s|\\w*)\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"ts": {
		{
			Language: "XML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("<TS\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "TypeScript",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"tsp": {
		{
			Language: "TypeSpec",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(import|using|namespace|interface|op|model|scalar|alias|union|enum)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "TSPLIB data",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^(NAME|TYPE|DIMENSION|EDGE_WEIGHT_TYPE|EDGE_WEIGHT_FORMAT)\\s*:"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"tst": {
		{
			Language: "GAP",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("gap> "),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Scilab",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"tsx": {
		{
			Language: "XML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?i:^\\s*<\\?xml\\s+version)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "TSX",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"txt": {
		{
			Language: "Text",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"typ": {
		{
			Language: "Typst",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^#(import|show|let|set)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "XML",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"url": {
		{
			Language: "INI",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\[InternetShortcut\\](?:\\r?\\n|\\r)([^\\s\\[][^\\r\\n]*(?:\\r?\\n|\\r)){0,20}URL="),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"v": {
		{
			Language: "Rocq Prover",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("(?:^|\\s)(?:Proof|Qed)\\.(?:$|\\s)|(?:^|\\s)Require[ \\t]+(Import|Export)\\s"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Verilog",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^[ \\t]*module\\s+[^\\s()]+\\s*\\#?\\(|^[ \\t]*`(?:define|ifdef|ifndef|include|timescale|pragma)|^[ \\t]*always[ \\t]*@|^[ \\t]*initial[ \\t]*(begin|@)"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "V",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\$(?:if|else)[ \\t]|^[ \\t]*fn\\s+[^\\s()]+\\(.*?\\).*?\\{|^[ \\t]*for\\s*\\{"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"vba": {
		{
			Language: "Vim Script",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^UseVimball"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "VBA",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"vcf": {
		{
			Language: "TSV",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\A##fileformat=VCF"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "vCard",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\ABEGIN:VCARD"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"w": {
		{
			Language: "OpenEdge ABL",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _DEFINITIONS"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "CWeb",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^@(<|\\w+\\.)"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"x": {
		{
			Language: "DirectX 3D File",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^xof 030(2|3)(?:txt|bin|tzip|bzip)\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "RPC",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\b(program|version)\\s+\\w+\\s*\\{|\\bunion\\s+\\w+\\s+switch\\s*\\("),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Logos",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^%(end|ctor|hook|group)\\b"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Linker Script",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("OUTPUT_ARCH\\(|OUTPUT_FORMAT\\(|SECTIONS"),
			},
			Negative: []*regexp.Regexp{},
		},
	},
	"yaml": {
		{
			Language: "MiniYAML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\t+.*?[^\\s:].*?:"),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("---"),
			},
		},
		{
			Language: "OASv2-yaml",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("swagger:\\s?'?\"?2.[0-9.]+'?\"?"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "OASv3-yaml",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("openapi:\\s?'?\"?3.[0-9.]+'?\"?"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "YAML",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"yml": {
		{
			Language: "MiniYAML",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("^\\t+.*?[^\\s:].*?:"),
			},
			Negative: []*regexp.Regexp{
				regexp.MustCompile("---"),
			},
		},
		{
			Language: "OASv2-yaml",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("swagger:\\s?'?\"?2.[0-9.]+'?\"?"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "OASv3-yaml",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("openapi:\\s?'?\"?3.[0-9.]+'?\"?"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "YAML",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
	"yy": {
		{
			Language: "JSON",
			Patterns: []*regexp.Regexp{
				regexp.MustCompile("\\A\\s*[{\\[]"),
			},
			Negative: []*regexp.Regexp{},
		},
		{
			Language: "Yacc",
			Patterns: []*regexp.Regexp{},
			Negative: []*regexp.Regexp{},
		},
	},
}
