package types

var AmbiguousExtensionMap = map[string][]string{
	"1":          []string{"Roff", "Roff Manpage"},
	"1in":        []string{"Roff", "Roff Manpage"},
	"1m":         []string{"Roff", "Roff Manpage"},
	"1x":         []string{"Roff", "Roff Manpage"},
	"2":          []string{"Roff", "Roff Manpage"},
	"3":          []string{"Roff", "Roff Manpage"},
	"3in":        []string{"Roff", "Roff Manpage"},
	"3m":         []string{"Roff", "Roff Manpage"},
	"3p":         []string{"Roff", "Roff Manpage"},
	"3pm":        []string{"Roff", "Roff Manpage"},
	"3qt":        []string{"Roff", "Roff Manpage"},
	"3x":         []string{"Roff", "Roff Manpage"},
	"4":          []string{"Roff", "Roff Manpage"},
	"5":          []string{"Roff", "Roff Manpage"},
	"6":          []string{"Roff", "Roff Manpage"},
	"7":          []string{"Roff", "Roff Manpage"},
	"8":          []string{"Roff", "Roff Manpage"},
	"9":          []string{"Roff", "Roff Manpage"},
	"al":         []string{"AL", "Perl"},
	"as":         []string{"ActionScript", "AngelScript"},
	"asc":        []string{"AGS Script", "AsciiDoc", "Public Key"},
	"ash":        []string{"AGS Script", "KoLmafia ASH"},
	"asm":        []string{"Assembly", "Motorola 68K Assembly"},
	"asy":        []string{"Asymptote", "LTspice Symbol"},
	"b":          []string{"Brainfuck", "Limbo"},
	"bas":        []string{"B4X", "BASIC", "FreeBASIC", "QuickBASIC", "VBA", "Visual Basic 6.0"},
	"bb":         []string{"BitBake", "BlitzBasic", "Clojure"},
	"bf":         []string{"Beef", "Befunge", "Brainfuck", "HyPhy"},
	"bi":         []string{"FreeBASIC", "QuickBASIC"},
	"brd":        []string{"Eagle", "KiCad Legacy Layout"},
	"bs":         []string{"Bikeshed", "Bluespec BH", "BrighterScript"},
	"bst":        []string{"BibTeX Style", "BuildStream"},
	"cairo":      []string{"Cairo", "Cairo Zero"},
	"cake":       []string{"C#", "CoffeeScript"},
	"cfg":        []string{"HAProxy", "INI"},
	"cgi":        []string{"Perl", "Python", "Shell"},
	"ch":         []string{"Charity", "xBase"},
	"cl":         []string{"Common Lisp", "Cool", "OpenCL"},
	"cls":        []string{"Apex", "ObjectScript", "OpenEdge ABL", "TeX", "VBA", "Visual Basic 6.0"},
	"cp":         []string{"C++", "Component Pascal"},
	"cs":         []string{"C#", "Smalltalk"},
	"csl":        []string{"Kusto", "XML"},
	"cue":        []string{"CUE", "Cue Sheet"},
	"d":          []string{"D", "DTrace", "Makefile"},
	"ddl":        []string{"PLSQL", "SQL"},
	"dsc":        []string{"Debian Package Control File", "DenizenScript"},
	"dsp":        []string{"Faust", "Microsoft Developer Studio Project"},
	"e":          []string{"E", "Eiffel", "Euphoria"},
	"ecl":        []string{"ECL", "ECLiPSe"},
	"es":         []string{"Erlang", "JavaScript"},
	"ex":         []string{"Elixir", "Euphoria"},
	"f":          []string{"Filebench WML", "Forth", "Fortran"},
	"fcgi":       []string{"Lua", "PHP", "Perl", "Python", "Ruby", "Shell"},
	"for":        []string{"Formatted", "Forth", "Fortran"},
	"fr":         []string{"Forth", "Frege", "Text"},
	"frag":       []string{"GLSL", "JavaScript"},
	"frm":        []string{"INI", "VBA", "Visual Basic 6.0"},
	"fs":         []string{"F#", "Filterscript", "Forth", "GLSL"},
	"ftl":        []string{"Fluent", "FreeMarker"},
	"fx":         []string{"FLUX", "HLSL"},
	"g":          []string{"G-code", "GAP"},
	"gd":         []string{"GAP", "GDScript"},
	"gml":        []string{"Game Maker Language", "Gerber Image", "Graph Modeling Language", "XML"},
	"gs":         []string{"GLSL", "Genie", "Gosu", "JavaScript"},
	"gst":        []string{"Gosu", "XML"},
	"gts":        []string{"Gerber Image", "Glimmer TS"},
	"h":          []string{"C", "C++", "Objective-C"},
	"hh":         []string{"C++", "Hack"},
	"html":       []string{"Ecmarkup", "HTML"},
	"i":          []string{"Assembly", "Motorola 68K Assembly", "SWIG"},
	"ice":        []string{"JSON", "Slice"},
	"inc":        []string{"Assembly", "BitBake", "C++", "HTML", "Motorola 68K Assembly", "NASL", "PHP", "POV-Ray SDL", "Pascal", "Pawn", "SQL", "SourcePawn"},
	"j":          []string{"Jasmin", "Objective-J"},
	"jq":         []string{"JSONiq", "jq"},
	"json":       []string{"JSON", "OASv2-json", "OASv3-json"},
	"k":          []string{"KCL", "KFramework"},
	"ks":         []string{"KerboScript", "Kickstart"},
	"l":          []string{"Common Lisp", "Lex", "PicoLisp", "Roff"},
	"lean":       []string{"Lean", "Lean 4"},
	"lisp":       []string{"Common Lisp", "NewLisp"},
	"lp":         []string{"Answer Set Programming", "Lambdapi", "Linear Programming"},
	"ls":         []string{"LiveScript", "LoomScript"},
	"lsp":        []string{"Common Lisp", "NewLisp"},
	"m":          []string{"Limbo", "M", "MATLAB", "MUF", "Mercury", "Objective-C", "Wolfram Language"},
	"m4":         []string{"M4", "M4Sugar"},
	"man":        []string{"Roff", "Roff Manpage"},
	"mask":       []string{"Mask", "Unity3D Asset"},
	"mc":         []string{"M4", "Monkey C", "Win32 Message File"},
	"md":         []string{"GCC Machine Description", "Markdown"},
	"mdoc":       []string{"Roff", "Roff Manpage"},
	"ml":         []string{"OCaml", "Standard ML"},
	"mm":         []string{"Objective-C++", "XML"},
	"mo":         []string{"Modelica", "Motoko"},
	"mod":        []string{"AMPL", "Linux Kernel Module", "Modula-2", "NMODL", "XML"},
	"mojo":       []string{"Mojo", "XML"},
	"moo":        []string{"Mercury", "Moocode"},
	"mps":        []string{"JetBrains MPS", "Mathematical Programming System"},
	"mqh":        []string{"MQL4", "MQL5"},
	"ms":         []string{"MAXScript", "Roff", "Unix Assembly"},
	"msg":        []string{"OMNeT++ MSG", "ROS Interface"},
	"n":          []string{"Nemerle", "Roff"},
	"nas":        []string{"Assembly", "Nasal"},
	"nb":         []string{"Text", "Wolfram Language"},
	"ncl":        []string{"Gerber Image", "NCL", "Nickel", "Text", "XML"},
	"nl":         []string{"NL", "NewLisp"},
	"nr":         []string{"Noir", "Roff"},
	"nu":         []string{"Nu", "Nushell"},
	"odin":       []string{"Object Data Instance Notation", "Odin"},
	"p":          []string{"Gnuplot", "OpenEdge ABL"},
	"pbt":        []string{"PowerBuilder", "Protocol Buffer Text Format"},
	"pc":         []string{"Pro*C", "pkg-config"},
	"php":        []string{"Hack", "PHP"},
	"pkl":        []string{"Pickle", "Pkl"},
	"pl":         []string{"Perl", "Prolog", "Raku"},
	"plist":      []string{"OpenStep Property List", "XML Property List"},
	"plt":        []string{"Gnuplot", "Prolog"},
	"pluginspec": []string{"Ruby", "XML"},
	"pm":         []string{"Perl", "Raku", "X PixMap"},
	"pod":        []string{"Pod", "Pod 6"},
	"pp":         []string{"Pascal", "Puppet"},
	"prc":        []string{"PLSQL", "SQL"},
	"pro":        []string{"IDL", "INI", "Proguard", "Prolog", "QMake"},
	"properties": []string{"INI", "Java Properties"},
	"q":          []string{"HiveQL", "q"},
	"qs":         []string{"Q#", "Qt Script"},
	"r":          []string{"R", "Rebol", "Rez"},
	"re":         []string{"C++", "Reason"},
	"reds":       []string{"Red", "Redscript"},
	"res":        []string{"ReScript", "XML"},
	"rno":        []string{"RUNOFF", "Roff"},
	"rpy":        []string{"Python", "Ren'Py"},
	"rs":         []string{"RenderScript", "Rust", "XML"},
	"rsc":        []string{"Rascal", "RouterOS Script"},
	"s":          []string{"Assembly", "Motorola 68K Assembly", "Unix Assembly"},
	"sc":         []string{"Scala", "SuperCollider"},
	"scd":        []string{"Markdown", "SuperCollider"},
	"sch":        []string{"Eagle", "KiCad Schematic", "Scheme", "XML"},
	"scm":        []string{"Scheme", "Tree-sitter Query"},
	"shader":     []string{"GLSL", "ShaderLab"},
	"sls":        []string{"SaltStack", "Scheme"},
	"sol":        []string{"Gerber Image", "Solidity"},
	"spec":       []string{"Python", "RPM Spec", "Ruby"},
	"sql":        []string{"PLSQL", "PLpgSQL", "SQL", "SQLPL", "TSQL"},
	"srt":        []string{"SRecode Template", "SubRip Text"},
	"st":         []string{"Smalltalk", "StringTemplate"},
	"star":       []string{"STAR", "Starlark"},
	"svx":        []string{"Survex data", "mdsvex"},
	"sw":         []string{"Sway", "XML"},
	"t":          []string{"Perl", "Raku", "Terra", "Turing"},
	"tact":       []string{"JSON", "Tact"},
	"tl":         []string{"Teal", "Type Language"},
	"toc":        []string{"TeX", "World of Warcraft Addon Data"},
	"tpl":        []string{"Go Template", "Smarty"},
	"trigger":    []string{"Apex", "Shell"},
	"ts":         []string{"TypeScript", "XML"},
	"tsp":        []string{"TSPLIB data", "TypeSpec"},
	"tst":        []string{"GAP", "Scilab"},
	"tsx":        []string{"TSX", "XML"},
	"txt":        []string{"Text", "Adblock Filter List", "Vim Help File"},
	"typ":        []string{"Typst", "XML"},
	"v":          []string{"Rocq Prover", "V", "Verilog"},
	"vba":        []string{"VBA", "Vim Script"},
	"vcf":        []string{"TSV", "vCard"},
	"vhost":      []string{"ApacheConf", "Nginx"},
	"w":          []string{"CWeb", "OpenEdge ABL"},
	"workflow":   []string{"HCL", "XML"},
	"x":          []string{"DirectX 3D File", "Linker Script", "Logos", "RPC"},
	"yaml":       []string{"MiniYAML", "OASv2-yaml", "OASv3-yaml", "YAML"},
	"yml":        []string{"MiniYAML", "OASv2-yaml", "OASv3-yaml", "YAML"},
	"yy":         []string{"JSON", "Yacc"},
}
