package types

var ExtensionMap = map[string]string{
	"2da":                  "2-Dimensional Array",
	"4DForm":               "JSON",
	"4DProject":            "JSON",
	"4dm":                  "4D",
	"4gl":                  "Genero 4gl",
	"4th":                  "Forth",
	"6pl":                  "Raku",
	"6pm":                  "Raku",
	"8xp":                  "TI Program",
	"8xp.txt":              "TI Program",
	"Dsr":                  "Visual Basic 6.0",
	"JSON-tmLanguage":      "JSON",
	"OutJob":               "Altium Designer",
	"PcbDoc":               "Altium Designer",
	"PrjPCB":               "Altium Designer",
	"SchDoc":               "Altium Designer",
	"TextGrid":             "TextGrid",
	"_coffee":              "CoffeeScript",
	"_js":                  "JavaScript",
	"_ls":                  "LiveScript",
	"a51":                  "Assembly",
	"abap":                 "ABAP",
	"abnf":                 "ABNF",
	"action":               "ROS Interface",
	"ada":                  "Ada",
	"adb":                  "Ada",
	"adml":                 "XML",
	"admx":                 "XML",
	"ado":                  "Stata",
	"adoc":                 "AsciiDoc",
	"adp":                  "Tcl",
	"ads":                  "Ada",
	"afm":                  "Adobe Font Metrics",
	"agc":                  "Apollo Guidance Computer",
	"agda":                 "Agda",
	"ahk":                  "AutoHotkey",
	"ahkl":                 "AutoHotkey",
	"aidl":                 "AIDL",
	"aj":                   "AspectJ",
	"ak":                   "Aiken",
	"alg":                  "ALGOL",
	"als":                  "Alloy",
	"ampl":                 "AMPL",
	"angelscript":          "AngelScript",
	"anim":                 "Unity3D Asset",
	"ant":                  "XML",
	"antlers.html":         "Antlers",
	"antlers.php":          "Antlers",
	"antlers.xml":          "Antlers",
	"apacheconf":           "ApacheConf",
	"apex":                 "Apex",
	"apib":                 "API Blueprint",
	"apl":                  "APL",
	"app":                  "Erlang",
	"app.src":              "Erlang",
	"applescript":          "AppleScript",
	"arc":                  "Arc",
	"arpa":                 "DNS Zone",
	"arr":                  "Pyret",
	"asax":                 "ASP.NET",
	"asciidoc":             "AsciiDoc",
	"ascx":                 "ASP.NET",
	"asd":                  "Common Lisp",
	"asddls":               "ABAP CDS",
	"ashx":                 "ASP.NET",
	"asl":                  "ASL",
	"asmx":                 "ASP.NET",
	"asn":                  "ASN.1",
	"asn1":                 "ASN.1",
	"asp":                  "Classic ASP",
	"aspx":                 "ASP.NET",
	"asset":                "Unity3D Asset",
	"astro":                "Astro",
	"au3":                  "AutoIt",
	"aug":                  "Augeas",
	"auk":                  "Awk",
	"aux":                  "TeX",
	"avdl":                 "Avro IDL",
	"avsc":                 "JSON",
	"aw":                   "PHP",
	"awk":                  "Awk",
	"axaml":                "XML",
	"axd":                  "ASP.NET",
	"axi":                  "NetLinx",
	"axi.erb":              "NetLinx+ERB",
	"axml":                 "XML",
	"axs":                  "NetLinx",
	"axs.erb":              "NetLinx+ERB",
	"bal":                  "Ballerina",
	"baml":                 "BAML",
	"bash":                 "Shell",
	"bat":                  "Batchfile",
	"bats":                 "Shell",
	"bbappend":             "BitBake",
	"bbclass":              "BitBake",
	"bbx":                  "TeX",
	"bdf":                  "Glyph Bitmap Distribution Format",
	"bdy":                  "PLSQL",
	"be":                   "Berry",
	"befunge":              "Befunge",
	"bib":                  "BibTeX",
	"bibtex":               "BibTeX",
	"bicep":                "Bicep",
	"bicepparam":           "Bicep",
	"bison":                "Bison",
	"blade":                "Blade",
	"blade.php":            "Blade",
	"blp":                  "Blueprint",
	"bmx":                  "BlitzMax",
	"bones":                "JavaScript",
	"boo":                  "Boo",
	"boot":                 "Clojure",
	"bpl":                  "Boogie",
	"bqn":                  "BQN",
	"bro":                  "Zeek",
	"brs":                  "Brightscript",
	"bru":                  "Bru",
	"bsl":                  "1C Enterprise",
	"bsv":                  "Bluespec",
	"builder":              "Ruby",
	"builds":               "XML",
	"bzl":                  "Starlark",
	"c":                    "C",
	"c++":                  "C++",
	"c++-objdump":          "Cpp-ObjDump",
	"c++objdump":           "Cpp-ObjDump",
	"c-objdump":            "C-ObjDump",
	"c3":                   "C3",
	"cabal":                "Cabal Config",
	"caddyfile":            "Caddyfile",
	"capnp":                "Cap'n Proto",
	"carbon":               "Carbon",
	"cats":                 "C",
	"cbl":                  "COBOL",
	"cbx":                  "TeX",
	"cc":                   "C++",
	"ccp":                  "COBOL",
	"ccproj":               "XML",
	"ccxml":                "XML",
	"cdc":                  "Cadence",
	"cdf":                  "Wolfram Language",
	"cds":                  "CAP CDS",
	"ceylon":               "Ceylon",
	"cfc":                  "ColdFusion CFC",
	"cfm":                  "ColdFusion",
	"cfml":                 "ColdFusion",
	"cginc":                "HLSL",
	"chem":                 "Pic",
	"chpl":                 "Chapel",
	"chs":                  "C2hs Haskell",
	"cil":                  "CIL",
	"circom":               "Circom",
	"cirru":                "Cirru",
	"cj":                   "Cangjie",
	"cjs":                  "JavaScript",
	"cjsx":                 "CoffeeScript",
	"ck":                   "ChucK",
	"cl2":                  "Clojure",
	"clar":                 "Clarity",
	"click":                "Click",
	"clixml":               "XML",
	"clj":                  "Clojure",
	"cljc":                 "Clojure",
	"cljs":                 "Clojure",
	"cljs.hl":              "Clojure",
	"cljscm":               "Clojure",
	"cljx":                 "Clojure",
	"clp":                  "CLIPS",
	"clue":                 "Clue",
	"clw":                  "Clarion",
	"cmake":                "CMake",
	"cmake.in":             "CMake",
	"cmd":                  "Batchfile",
	"cmp":                  "Gerber Image",
	"cnc":                  "G-code",
	"cnf":                  "INI",
	"cob":                  "COBOL",
	"cobol":                "COBOL",
	"cocci":                "SmPL",
	"code-snippets":        "JSON with Comments",
	"code-workspace":       "JSON with Comments",
	"coffee":               "CoffeeScript",
	"coffee.md":            "Literate CoffeeScript",
	"com":                  "DIGITAL Command Language",
	"command":              "Shell",
	"conll":                "CoNLL-U",
	"conllu":               "CoNLL-U",
	"container":            "INI",
	"containerfile":        "Dockerfile",
	"cook":                 "Cooklang",
	"coq":                  "Rocq Prover",
	"cpp":                  "C++",
	"cpp-objdump":          "Cpp-ObjDump",
	"cppm":                 "C++",
	"cppobjdump":           "Cpp-ObjDump",
	"cproject":             "XML",
	"cps":                  "Component Pascal",
	"cpy":                  "COBOL",
	"cql":                  "CQL",
	"cr":                   "Crystal",
	"crc32":                "Checksums",
	"creole":               "Creole",
	"cs.pp":                "C#",
	"csc":                  "GSC",
	"cscfg":                "XML",
	"csd":                  "Csound Document",
	"csdef":                "XML",
	"csh":                  "Tcsh",
	"cshtml":               "HTML+Razor",
	"cson":                 "CSON",
	"csproj":               "XML",
	"css":                  "CSS",
	"csv":                  "CSV",
	"csx":                  "C#",
	"ct":                   "XML",
	"ctl":                  "Visual Basic 6.0",
	"ctp":                  "PHP",
	"cts":                  "TypeScript",
	"cu":                   "Cuda",
	"cuh":                  "Cuda",
	"curry":                "Curry",
	"cw":                   "Redcode",
	"cwl":                  "Common Workflow Language",
	"cxx":                  "C++",
	"cxx-objdump":          "Cpp-ObjDump",
	"cy":                   "Cycript",
	"cylc":                 "Cylc",
	"cyp":                  "Cypher",
	"cypher":               "Cypher",
	"d-objdump":            "D-ObjDump",
	"d2":                   "D2",
	"dae":                  "COLLADA",
	"darcspatch":           "Darcs Patch",
	"dart":                 "Dart",
	"das":                  "Daslang",
	"dats":                 "ATS",
	"db2":                  "SQLPL",
	"dcl":                  "Clean",
	"decls":                "BlitzBasic",
	"depproj":              "XML",
	"desktop":              "desktop",
	"desktop.in":           "desktop",
	"dfm":                  "Pascal",
	"dfy":                  "Dafny",
	"dhall":                "Dhall",
	"di":                   "D",
	"diff":                 "Diff",
	"dircolors":            "dircolors",
	"dita":                 "XML",
	"ditamap":              "XML",
	"ditaval":              "XML",
	"djs":                  "Dogescript",
	"dll.config":           "XML",
	"dlm":                  "IDL",
	"dm":                   "DM",
	"do":                   "Stata",
	"dockerfile":           "Dockerfile",
	"dof":                  "INI",
	"doh":                  "Stata",
	"dot":                  "Graphviz (DOT)",
	"dotsettings":          "XML",
	"dpatch":               "Darcs Patch",
	"dpr":                  "Pascal",
	"druby":                "Mirah",
	"dsl":                  "ASL",
	"dtx":                  "TeX",
	"duby":                 "Mirah",
	"dwl":                  "DataWeave",
	"dyalog":               "APL",
	"dyl":                  "Dylan",
	"dylan":                "Dylan",
	"dzn":                  "MiniZinc Data",
	"eam.fs":               "Formatted",
	"eb":                   "Easybuild",
	"ebnf":                 "EBNF",
	"ebuild":               "Gentoo Ebuild",
	"ec":                   "eC",
	"eclass":               "Gentoo Eclass",
	"eclxml":               "ECL",
	"ecr":                  "HTML+ECR",
	"ect":                  "EJS",
	"edc":                  "Edje Data Collection",
	"edge":                 "Edge",
	"edgeql":               "EdgeQL",
	"editorconfig":         "EditorConfig",
	"edn":                  "edn",
	"eh":                   "eC",
	"ejs":                  "EJS",
	"ejs.t":                "EJS",
	"el":                   "Emacs Lisp",
	"eliom":                "OCaml",
	"eliomi":               "OCaml",
	"elm":                  "Elm",
	"elv":                  "Elvish",
	"em":                   "EmberScript",
	"emacs":                "Emacs Lisp",
	"emacs.desktop":        "Emacs Lisp",
	"emberscript":          "EmberScript",
	"eml":                  "E-mail",
	"env":                  "Dotenv",
	"epj":                  "Ecere Projects",
	"eps":                  "PostScript",
	"epsi":                 "PostScript",
	"eq":                   "EQ",
	"erb":                  "HTML+ERB",
	"erb.deface":           "HTML+ERB",
	"erl":                  "Erlang",
	"es6":                  "JavaScript",
	"escript":              "Erlang",
	"esdl":                 "EdgeQL",
	"exs":                  "Elixir",
	"eye":                  "Ruby",
	"f03":                  "Fortran Free Form",
	"f08":                  "Fortran Free Form",
	"f77":                  "Fortran",
	"f90":                  "Fortran Free Form",
	"f95":                  "Fortran Free Form",
	"factor":               "Factor",
	"fan":                  "Fantom",
	"fancypack":            "Fancy",
	"fbs":                  "FlatBuffers",
	"fea":                  "OpenType Feature File",
	"feature":              "Gherkin",
	"filters":              "XML",
	"fir":                  "FIRRTL",
	"fish":                 "fish",
	"flex":                 "JFlex",
	"flf":                  "FIGlet Font",
	"flix":                 "Flix",
	"flux":                 "FLUX",
	"fnc":                  "PLSQL",
	"fnl":                  "Fennel",
	"forth":                "Forth",
	"fp":                   "GLSL",
	"fpp":                  "Fortran",
	"frg":                  "GLSL",
	"frt":                  "Forth",
	"fsh":                  "GLSL",
	"fshader":              "GLSL",
	"fsi":                  "F#",
	"fsproj":               "XML",
	"fst":                  "F*",
	"fsti":                 "F*",
	"fsx":                  "F#",
	"fth":                  "Forth",
	"ftlh":                 "FreeMarker",
	"fun":                  "Standard ML",
	"fut":                  "Futhark",
	"fxh":                  "HLSL",
	"fxml":                 "XML",
	"fy":                   "Fancy",
	"g4":                   "ANTLR",
	"gaml":                 "GAML",
	"gap":                  "GAP",
	"gawk":                 "Awk",
	"gbl":                  "Gerber Image",
	"gbo":                  "Gerber Image",
	"gbp":                  "Gerber Image",
	"gbr":                  "Gerber Image",
	"gbs":                  "Gerber Image",
	"gco":                  "G-code",
	"gcode":                "G-code",
	"gdb":                  "GDB",
	"gdbinit":              "GDB",
	"gdnlib":               "Godot Resource",
	"gdns":                 "Godot Resource",
	"gdshader":             "GDShader",
	"gdshaderinc":          "GDShader",
	"ged":                  "GEDCOM",
	"gemspec":              "Ruby",
	"geo":                  "GLSL",
	"geojson":              "JSON",
	"geom":                 "GLSL",
	"gf":                   "Grammatical Framework",
	"gi":                   "GAP",
	"gitconfig":            "Git Config",
	"gitignore":            "Ignore List",
	"gjs":                  "Glimmer JS",
	"gko":                  "Gerber Image",
	"glade":                "XML",
	"gleam":                "Gleam",
	"glf":                  "Glyph",
	"glsl":                 "GLSL",
	"glslf":                "GLSL",
	"glslv":                "GLSL",
	"gltf":                 "JSON",
	"glyphs":               "OpenStep Property List",
	"gmi":                  "Gemini",
	"gms":                  "GAMS",
	"gmx":                  "XML",
	"gn":                   "GN",
	"gni":                  "GN",
	"gnu":                  "Gnuplot",
	"gnuplot":              "Gnuplot",
	"go":                   "Go",
	"god":                  "Ruby",
	"gohtml":               "Go Template",
	"golo":                 "Golo",
	"gotmpl":               "Go Template",
	"gp":                   "Gnuplot",
	"gpb":                  "Gerber Image",
	"gpt":                  "Gerber Image",
	"gpx":                  "XML",
	"gql":                  "GraphQL",
	"grace":                "Grace",
	"gradle":               "Gradle",
	"gradle.kts":           "Gradle Kotlin DSL",
	"graphql":              "GraphQL",
	"graphqls":             "GraphQL",
	"groovy":               "Groovy",
	"grt":                  "Groovy",
	"grxml":                "XML",
	"gsc":                  "GSC",
	"gsh":                  "GSC",
	"gshader":              "GLSL",
	"gsp":                  "Groovy Server Pages",
	"gsx":                  "Gosu",
	"gtkrc":                "GtkRC",
	"gtl":                  "Gerber Image",
	"gto":                  "Gerber Image",
	"gtp":                  "Gerber Image",
	"gtpl":                 "Groovy",
	"gv":                   "Graphviz (DOT)",
	"gvy":                  "Groovy",
	"gyp":                  "Python",
	"gypi":                 "Python",
	"h++":                  "C++",
	"h.in":                 "C",
	"ha":                   "Hare",
	"hack":                 "Hack",
	"haml":                 "Haml",
	"haml.deface":          "Haml",
	"handlebars":           "Handlebars",
	"har":                  "JSON",
	"hats":                 "ATS",
	"hb":                   "Harbour",
	"hbs":                  "Handlebars",
	"hc":                   "HolyC",
	"hcl":                  "HCL",
	"heex":                 "HTML+EEX",
	"hhi":                  "Hack",
	"hic":                  "Clojure",
	"hip":                  "HIP",
	"hlean":                "Lean",
	"hlsl":                 "HLSL",
	"hlsli":                "HLSL",
	"hocon":                "HOCON",
	"hoon":                 "hoon",
	"hpp":                  "C++",
	"hqf":                  "SQF",
	"hql":                  "HiveQL",
	"hrl":                  "Erlang",
	"hs":                   "Haskell",
	"hs-boot":              "Haskell",
	"hsc":                  "Haskell",
	"hta":                  "HTML",
	"htm":                  "HTML",
	"html.eex":             "HTML+EEX",
	"html.hl":              "HTML",
	"html.tmpl":            "Go Template",
	"http":                 "HTTP",
	"hurl":                 "Hurl",
	"hx":                   "Haxe",
	"hxml":                 "HXML",
	"hxsl":                 "Haxe",
	"hxx":                  "C++",
	"hy":                   "Hy",
	"hzp":                  "XML",
	"i3":                   "Modula-3",
	"i7x":                  "Inform 7",
	"ical":                 "iCalendar",
	"iced":                 "CoffeeScript",
	"icl":                  "Clean",
	"icls":                 "XML",
	"ics":                  "iCalendar",
	"idc":                  "C",
	"idr":                  "Idris",
	"ig":                   "Modula-3",
	"ihlp":                 "Stata",
	"ijm":                  "ImageJ Macro",
	"ijs":                  "J",
	"ik":                   "Ioke",
	"il":                   "IL Assembly",
	"ily":                  "LilyPond",
	"imba":                 "Imba",
	"iml":                  "XML",
	"ini":                  "INI",
	"ink":                  "Ink",
	"inl":                  "C++",
	"ino":                  "C++",
	"ins":                  "TeX",
	"intr":                 "Dylan",
	"io":                   "Io",
	"iol":                  "Jolie",
	"ipf":                  "IGOR Pro",
	"ipp":                  "C++",
	"ipynb":                "Jupyter Notebook",
	"irclog":               "IRC log",
	"isl":                  "Inno Setup",
	"ispc":                 "ISPC",
	"iss":                  "Inno Setup",
	"iuml":                 "PlantUML",
	"ivy":                  "XML",
	"ixx":                  "C++",
	"j2":                   "Jinja",
	"jac":                  "Jac",
	"jade":                 "Pug",
	"jai":                  "Jai",
	"jake":                 "JavaScript",
	"janet":                "Janet",
	"jav":                  "Java",
	"java":                 "Java",
	"javascript":           "JavaScript",
	"jbuilder":             "Ruby",
	"jcl":                  "JCL",
	"jelly":                "XML",
	"jflex":                "JFlex",
	"jinja":                "Jinja",
	"jinja2":               "Jinja",
	"jison":                "Jison",
	"jisonlex":             "Jison Lex",
	"jl":                   "Julia",
	"js":                   "JavaScript",
	"js.erb":               "JavaScript+ERB",
	"jsb":                  "JavaScript",
	"jscad":                "JavaScript",
	"jsfl":                 "JavaScript",
	"jsh":                  "Java",
	"jslib":                "JavaScript",
	"jsm":                  "JavaScript",
	"json.example":         "JSON",
	"json5":                "JSON5",
	"jsonc":                "JSON with Comments",
	"jsonl":                "JSON",
	"jsonld":               "JSONLD",
	"jsonnet":              "Jsonnet",
	"jsp":                  "Java Server Pages",
	"jspre":                "JavaScript",
	"jsproj":               "XML",
	"jss":                  "JavaScript",
	"jst":                  "EJS",
	"jsx":                  "JavaScript",
	"jte":                  "Java Template Engine",
	"just":                 "Just",
	"kak":                  "KakouneScript",
	"kdl":                  "KDL",
	"kicad_mod":            "KiCad Layout",
	"kicad_pcb":            "KiCad Layout",
	"kicad_sch":            "KiCad Schematic",
	"kicad_sym":            "KiCad Schematic",
	"kicad_wks":            "KiCad Layout",
	"kid":                  "Genshi",
	"kit":                  "Kit",
	"kk":                   "Koka",
	"kml":                  "XML",
	"kojo":                 "Scala",
	"kql":                  "Kusto",
	"krl":                  "KRL",
	"ksh":                  "Shell",
	"ksy":                  "Kaitai Struct",
	"kt":                   "Kotlin",
	"ktm":                  "Kotlin",
	"kts":                  "Kotlin",
	"kv":                   "kvlang",
	"lagda":                "Literate Agda",
	"langium":              "Langium",
	"lark":                 "Lark",
	"las":                  "Lasso",
	"lasso":                "Lasso",
	"lasso8":               "Lasso",
	"lasso9":               "Lasso",
	"latte":                "Latte",
	"launch":               "XML",
	"lbx":                  "TeX",
	"ld":                   "Linker Script",
	"lds":                  "Linker Script",
	"leex":                 "HTML+EEX",
	"lektorproject":        "INI",
	"leo":                  "Leo",
	"less":                 "Less",
	"lex":                  "Lex",
	"lfe":                  "LFE",
	"lgt":                  "Logtalk",
	"lhs":                  "Literate Haskell",
	"libsonnet":            "Jsonnet",
	"lid":                  "Dylan",
	"lidr":                 "Idris",
	"ligo":                 "LigoLANG",
	"linq":                 "C#",
	"liq":                  "Liquidsoap",
	"liquid":               "Liquid",
	"litcoffee":            "Literate CoffeeScript",
	"livecodescript":       "LiveCode Script",
	"livemd":               "Markdown",
	"lkml":                 "LookML",
	"ll":                   "LLVM",
	"lmi":                  "Python",
	"logtalk":              "Logtalk",
	"lol":                  "LOLCODE",
	"lookml":               "LookML",
	"lpr":                  "Pascal",
	"lsl":                  "LSL",
	"lslp":                 "LSL",
	"ltx":                  "TeX",
	"lua":                  "Lua",
	"luau":                 "Luau",
	"lvclass":              "LabVIEW",
	"lvlib":                "LabVIEW",
	"lvproj":               "LabVIEW",
	"ly":                   "LilyPond",
	"m2":                   "Macaulay2",
	"m3":                   "Modula-3",
	"m3u":                  "M3U",
	"m3u8":                 "M3U",
	"ma":                   "Wolfram Language",
	"mak":                  "Makefile",
	"make":                 "Makefile",
	"makefile":             "Makefile",
	"mako":                 "Mako",
	"mao":                  "Mako",
	"markdown":             "Markdown",
	"marko":                "Marko",
	"mat":                  "Unity3D Asset",
	"mata":                 "Stata",
	"matah":                "Stata",
	"mathematica":          "Wolfram Language",
	"matlab":               "MATLAB",
	"mawk":                 "Awk",
	"maxhelp":              "Max",
	"maxpat":               "Max",
	"maxproj":              "Max",
	"mbox":                 "E-mail",
	"mbt":                  "MoonBit",
	"mcfunction":           "mcfunction",
	"mch":                  "B (Formal Method)",
	"mcmeta":               "JSON",
	"mcr":                  "MAXScript",
	"md2":                  "Checksums",
	"md4":                  "Checksums",
	"md5":                  "Checksums",
	"mdown":                "Markdown",
	"mdpolicy":             "XML",
	"mdwn":                 "Markdown",
	"mdx":                  "MDX",
	"me":                   "Roff",
	"mediawiki":            "Wikitext",
	"mermaid":              "Mermaid",
	"meta":                 "Unity3D Asset",
	"metal":                "Metal",
	"metta":                "MeTTa",
	"mg":                   "Modula-3",
	"minid":                "MiniD",
	"mint":                 "Mint",
	"mir":                  "YAML",
	"mirah":                "Mirah",
	"mjml":                 "XML",
	"mjs":                  "JavaScript",
	"mk":                   "Makefile",
	"mkd":                  "Markdown",
	"mkdn":                 "Markdown",
	"mkdown":               "Markdown",
	"mkfile":               "Makefile",
	"mkii":                 "TeX",
	"mkiv":                 "TeX",
	"mkvi":                 "TeX",
	"ml4":                  "OCaml",
	"mli":                  "OCaml",
	"mligo":                "CameLIGO",
	"mlir":                 "MLIR",
	"mll":                  "OCaml",
	"mly":                  "OCaml",
	"mmd":                  "Mermaid",
	"mmk":                  "Module Management System",
	"mms":                  "Module Management System",
	"monkey":               "Monkey",
	"monkey2":              "Monkey",
	"moon":                 "MoonScript",
	"mount":                "INI",
	"move":                 "Move",
	"mpl":                  "JetBrains MPS",
	"mq4":                  "MQL4",
	"mq5":                  "MQL5",
	"mrc":                  "mIRC Script",
	"msd":                  "JetBrains MPS",
	"mspec":                "Ruby",
	"mss":                  "CartoCSS",
	"mt":                   "Wolfram Language",
	"mtl":                  "Wavefront Material",
	"mtml":                 "MTML",
	"mts":                  "TypeScript",
	"mu":                   "mupad",
	"mud":                  "ZIL",
	"muf":                  "MUF",
	"mumps":                "M",
	"muse":                 "Muse",
	"mustache":             "Mustache",
	"mxml":                 "XML",
	"mxt":                  "Max",
	"mysql":                "SQL",
	"myt":                  "Myghty",
	"mzn":                  "MiniZinc",
	"nanorc":               "nanorc",
	"nasl":                 "NASL",
	"nasm":                 "Assembly",
	"natvis":               "XML",
	"nawk":                 "Awk",
	"nbp":                  "Wolfram Language",
	"nc":                   "nesC",
	"ndproj":               "XML",
	"ne":                   "Nearley",
	"nearley":              "Nearley",
	"ned":                  "OMNeT++ NED",
	"neon":                 "NEON",
	"network":              "INI",
	"nf":                   "Nextflow",
	"nginx":                "Nginx",
	"nginxconf":            "Nginx",
	"ni":                   "Inform 7",
	"nim":                  "Nim",
	"nim.cfg":              "Nim",
	"nimble":               "Nim",
	"nimrod":               "Nim",
	"nims":                 "Nim",
	"ninja":                "Ninja",
	"nit":                  "Nit",
	"nix":                  "Nix",
	"njk":                  "Nunjucks",
	"njs":                  "JavaScript",
	"nlogo":                "NetLogo",
	"no":                   "Text",
	"nomad":                "HCL",
	"nproj":                "XML",
	"nqp":                  "Raku",
	"nse":                  "Lua",
	"nsh":                  "NSIS",
	"nsi":                  "NSIS",
	"nss":                  "NWScript",
	"numpy":                "NumPy",
	"numpyw":               "NumPy",
	"numsc":                "NumPy",
	"nuspec":               "XML",
	"nut":                  "Squirrel",
	"ny":                   "Common Lisp",
	"ob2":                  "Oberon",
	"obj":                  "Wavefront Object",
	"objdump":              "ObjDump",
	"odd":                  "XML",
	"ol":                   "Jolie",
	"omgrofl":              "Omgrofl",
	"ooc":                  "ooc",
	"opa":                  "Opa",
	"opal":                 "Opal",
	"opencl":               "OpenCL",
	"opy":                  "OverPy",
	"orc":                  "Csound",
	"org":                  "Org",
	"os":                   "1C Enterprise",
	"osm":                  "XML",
	"overpassql":           "OverpassQL",
	"owl":                  "Web Ontology Language",
	"ox":                   "Ox",
	"oxh":                  "Ox",
	"oxo":                  "Ox",
	"oxygene":              "Oxygene",
	"oz":                   "Oz",
	"p4":                   "P4",
	"p6":                   "Raku",
	"p6l":                  "Raku",
	"p6m":                  "Raku",
	"p8":                   "Lua",
	"pac":                  "JavaScript",
	"pact":                 "Pact",
	"pan":                  "Pan",
	"parrot":               "Parrot",
	"pas":                  "Pascal",
	"pascal":               "Pascal",
	"pasm":                 "Parrot Assembly",
	"pat":                  "Max",
	"patch":                "Diff",
	"pb":                   "PureBasic",
	"pbi":                  "PureBasic",
	"pbtxt":                "Protocol Buffer Text Format",
	"pc.in":                "pkg-config",
	"pck":                  "PLSQL",
	"pcss":                 "PostCSS",
	"pd":                   "Pure Data",
	"pd_lua":               "Lua",
	"pddl":                 "PDDL",
	"pde":                  "Processing",
	"peggy":                "PEG.js",
	"pegjs":                "PEG.js",
	"pep":                  "Pep8",
	"per":                  "Genero per",
	"perl":                 "Perl",
	"pfa":                  "PostScript",
	"pgsql":                "PLpgSQL",
	"ph":                   "Perl",
	"php3":                 "PHP",
	"php4":                 "PHP",
	"php5":                 "PHP",
	"phps":                 "PHP",
	"phpt":                 "PHP",
	"phtml":                "HTML+PHP",
	"pic":                  "Pic",
	"pig":                  "PigLatin",
	"pike":                 "Pike",
	"pir":                  "Parrot Internal Representation",
	"pkb":                  "PLSQL",
	"pkgproj":              "XML",
	"pks":                  "PLSQL",
	"pl6":                  "Raku",
	"plantuml":             "PlantUML",
	"plb":                  "PLSQL",
	"plot":                 "Gnuplot",
	"pls":                  "PLSQL",
	"plsql":                "PLSQL",
	"plx":                  "Perl",
	"pm6":                  "Raku",
	"pml":                  "Promela",
	"pmod":                 "Pike",
	"po":                   "Gettext Catalog",
	"pod6":                 "Pod 6",
	"podsl":                "Common Lisp",
	"podspec":              "Ruby",
	"pogo":                 "PogoScript",
	"polar":                "Polar",
	"pony":                 "Pony",
	"por":                  "Portugol",
	"postcss":              "PostCSS",
	"pot":                  "Gettext Catalog",
	"pov":                  "POV-Ray SDL",
	"pprx":                 "REXX",
	"pq":                   "Power Query",
	"praat":                "Praat",
	"prawn":                "Ruby",
	"prefab":               "Unity3D Asset",
	"prefs":                "INI",
	"prg":                  "xBase",
	"pri":                  "QMake",
	"prisma":               "Prisma",
	"proj":                 "XML",
	"prolog":               "Prolog",
	"props":                "XML",
	"proto":                "Protocol Buffer",
	"prw":                  "xBase",
	"ps":                   "PostScript",
	"ps1":                  "PowerShell",
	"ps1xml":               "XML",
	"psc":                  "Papyrus",
	"psc1":                 "XML",
	"psd1":                 "PowerShell",
	"psgi":                 "Perl",
	"psm1":                 "PowerShell",
	"pt":                   "XML",
	"pub":                  "Public Key",
	"pubxml":               "XML",
	"pug":                  "Pug",
	"puml":                 "PlantUML",
	"purs":                 "PureScript",
	"pwn":                  "Pawn",
	"pxd":                  "Cython",
	"pxi":                  "Cython",
	"py":                   "Python",
	"py3":                  "Python",
	"pyde":                 "Python",
	"pyi":                  "Python",
	"pyp":                  "Python",
	"pyt":                  "Python",
	"pytb":                 "Python traceback",
	"pyw":                  "Python",
	"pyx":                  "Cython",
	"qasm":                 "OpenQASM",
	"qbs":                  "QML",
	"qc":                   "QuakeC",
	"qhelp":                "XML",
	"ql":                   "CodeQL",
	"qll":                  "CodeQL",
	"qmd":                  "RMarkdown",
	"qml":                  "QML",
	"qnt":                  "Quint",
	"r2":                   "Rebol",
	"r3":                   "Rebol",
	"rabl":                 "Ruby",
	"rake":                 "Ruby",
	"raku":                 "Raku",
	"rakumod":              "Raku",
	"raml":                 "RAML",
	"rascript":             "RAScript",
	"raw":                  "Raw token data",
	"razor":                "HTML+Razor",
	"rb":                   "Ruby",
	"rbbas":                "REALbasic",
	"rbfrm":                "REALbasic",
	"rbi":                  "Ruby",
	"rbmnu":                "REALbasic",
	"rbres":                "REALbasic",
	"rbs":                  "RBS",
	"rbtbar":               "REALbasic",
	"rbuild":               "Ruby",
	"rbuistate":            "REALbasic",
	"rbw":                  "Ruby",
	"rbx":                  "Ruby",
	"rbxs":                 "Lua",
	"rchit":                "GLSL",
	"rd":                   "R",
	"rdf":                  "XML",
	"rdoc":                 "RDoc",
	"reb":                  "Rebol",
	"rebol":                "Rebol",
	"red":                  "Red",
	"reek":                 "YAML",
	"reg":                  "Windows Registry Entries",
	"regex":                "Regular Expression",
	"regexp":               "Regular Expression",
	"rego":                 "Open Policy Agent",
	"rei":                  "Reason",
	"religo":               "ReasonLIGO",
	"resi":                 "ReScript",
	"resource":             "RobotFramework",
	"rest":                 "reStructuredText",
	"rest.txt":             "reStructuredText",
	"resx":                 "XML",
	"rex":                  "REXX",
	"rexx":                 "REXX",
	"rg":                   "Rouge",
	"rhtml":                "HTML+ERB",
	"ring":                 "Ring",
	"riot":                 "Riot",
	"rkt":                  "Racket",
	"rktd":                 "Racket",
	"rktl":                 "Racket",
	"rl":                   "Ragel",
	"rmd":                  "RMarkdown",
	"rmiss":                "GLSL",
	"rnh":                  "RUNOFF",
	"rnw":                  "Sweave",
	"robot":                "RobotFramework",
	"roc":                  "Roc",
	"rockspec":             "Lua",
	"roff":                 "Roff",
	"ron":                  "RON",
	"ronn":                 "Markdown",
	"rpgle":                "RPGLE",
	"rq":                   "SPARQL",
	"rs.in":                "Rust",
	"rsh":                  "RenderScript",
	"rss":                  "XML",
	"rst":                  "reStructuredText",
	"rst.txt":              "reStructuredText",
	"rsx":                  "R",
	"rtf":                  "Rich Text Format",
	"ru":                   "Ruby",
	"ruby":                 "Ruby",
	"rviz":                 "YAML",
	"sage":                 "Sage",
	"sagews":               "Sage",
	"sail":                 "Sail",
	"sarif":                "JSON",
	"sas":                  "SAS",
	"sass":                 "Sass",
	"sats":                 "ATS",
	"sbatch":               "Shell",
	"sbt":                  "Scala",
	"scad":                 "OpenSCAD",
	"scala":                "Scala",
	"scaml":                "Scaml",
	"sce":                  "Scilab",
	"scenic":               "Scenic",
	"sci":                  "Scilab",
	"sco":                  "Csound Score",
	"scpt":                 "AppleScript",
	"scrbl":                "Racket",
	"scss":                 "SCSS",
	"scxml":                "XML",
	"sdc":                  "Tcl",
	"sed":                  "sed",
	"self":                 "Self",
	"service":              "INI",
	"sexp":                 "Common Lisp",
	"sfd":                  "Spline Font Database",
	"sfproj":               "XML",
	"sfv":                  "Simple File Verification",
	"sh":                   "Shell",
	"sh-session":           "ShellSession",
	"sh.in":                "Shell",
	"sha1":                 "Checksums",
	"sha2":                 "Checksums",
	"sha224":               "Checksums",
	"sha256":               "Checksums",
	"sha256sum":            "Checksums",
	"sha3":                 "Checksums",
	"sha384":               "Checksums",
	"sha512":               "Checksums",
	"shen":                 "Shen",
	"shproj":               "XML",
	"sieve":                "Sieve",
	"sig":                  "Standard ML",
	"sj":                   "Objective-J",
	"sjs":                  "JavaScript",
	"sl":                   "Slash",
	"slang":                "Slang",
	"sld":                  "Scheme",
	"slim":                 "Slim",
	"slint":                "Slint",
	"sln":                  "Microsoft Visual Studio Solution",
	"slnlaunch":            "JSON",
	"slnx":                 "XML",
	"slurm":                "Shell",
	"sma":                  "Pawn",
	"smali":                "Smali",
	"smithy":               "Smithy",
	"smk":                  "Snakemake",
	"sml":                  "Standard ML",
	"smt":                  "SMT",
	"smt2":                 "SMT",
	"snakefile":            "Snakemake",
	"snap":                 "Jest Snapshot",
	"snip":                 "Vim Snippet",
	"snippet":              "Vim Snippet",
	"snippets":             "Vim Snippet",
	"socket":               "INI",
	"soy":                  "Closure Templates",
	"sp":                   "SourcePawn",
	"sparql":               "SPARQL",
	"spc":                  "PLSQL",
	"spin":                 "Propeller Spin",
	"sps":                  "Scheme",
	"sqf":                  "SQF",
	"sqlrpgle":             "RPGLE",
	"sra":                  "PowerBuilder",
	"srdf":                 "XML",
	"sru":                  "PowerBuilder",
	"srv":                  "ROS Interface",
	"srw":                  "PowerBuilder",
	"ss":                   "Scheme",
	"ssjs":                 "JavaScript",
	"sss":                  "SugarSS",
	"stTheme":              "XML Property List",
	"stan":                 "Stan",
	"sthlp":                "Stata",
	"stl":                  "STL",
	"ston":                 "STON",
	"story":                "Gherkin",
	"storyboard":           "XML",
	"sty":                  "TeX",
	"styl":                 "Stylus",
	"sublime-build":        "JSON with Comments",
	"sublime-color-scheme": "JSON with Comments",
	"sublime-commands":     "JSON with Comments",
	"sublime-completions":  "JSON with Comments",
	"sublime-keymap":       "JSON with Comments",
	"sublime-macro":        "JSON with Comments",
	"sublime-menu":         "JSON with Comments",
	"sublime-mousemap":     "JSON with Comments",
	"sublime-project":      "JSON with Comments",
	"sublime-settings":     "JSON with Comments",
	"sublime-snippet":      "XML",
	"sublime-syntax":       "YAML",
	"sublime-theme":        "JSON with Comments",
	"sublime-workspace":    "JSON with Comments",
	"sublime_metrics":      "JSON with Comments",
	"sublime_session":      "JSON with Comments",
	"surql":                "SurrealQL",
	"sv":                   "SystemVerilog",
	"svelte":               "Svelte",
	"svg":                  "SVG",
	"svh":                  "SystemVerilog",
	"swg":                  "SWIG",
	"swift":                "Swift",
	"swig":                 "SWIG",
	"syntax":               "YAML",
	"tab":                  "SQL",
	"tac":                  "Python",
	"tag":                  "Java Server Pages",
	"talon":                "Talon",
	"target":               "INI",
	"targets":              "XML",
	"tcc":                  "C++",
	"tcl":                  "Tcl",
	"tcl.in":               "Tcl",
	"tcsh":                 "Tcsh",
	"te":                   "SELinux Policy",
	"tea":                  "Tea",
	"templ":                "templ",
	"tesc":                 "GLSL",
	"tese":                 "GLSL",
	"tex":                  "TeX",
	"texi":                 "Texinfo",
	"texinfo":              "Texinfo",
	"textile":              "Textile",
	"textproto":            "Protocol Buffer Text Format",
	"tf":                   "HCL",
	"tfstate":              "JSON",
	"tfstate.backup":       "JSON",
	"tftpl":                "Terraform Template",
	"tfvars":               "HCL",
	"thor":                 "Ruby",
	"thrift":               "Thrift",
	"thy":                  "Isabelle",
	"timer":                "INI",
	"tla":                  "TLA",
	"tlv":                  "TL-Verilog",
	"tm":                   "Tcl",
	"tmCommand":            "XML Property List",
	"tmLanguage":           "XML Property List",
	"tmPreferences":        "XML Property List",
	"tmSnippet":            "XML Property List",
	"tmTheme":              "XML Property List",
	"tmac":                 "Roff",
	"tmdl":                 "TMDL",
	"tml":                  "XML",
	"tmpl":                 "Go Template",
	"tmux":                 "Shell",
	"tofu":                 "HCL",
	"toit":                 "Toit",
	"toml":                 "TOML",
	"toml.example":         "TOML",
	"tool":                 "Shell",
	"topojson":             "JSON",
	"tpb":                  "PLSQL",
	"tpp":                  "C++",
	"tps":                  "PLSQL",
	"tres":                 "Godot Resource",
	"trg":                  "PLSQL",
	"tscn":                 "Godot Resource",
	"tsconfig.json":        "JSON with Comments",
	"tsv":                  "TSV",
	"ttl":                  "Turtle",
	"tu":                   "Turing",
	"twig":                 "Twig",
	"txi":                  "Texinfo",
	"txl":                  "TXL",
	"txtpb":                "Protocol Buffer Text Format",
	"txx":                  "C++",
	"uc":                   "UnrealScript",
	"udf":                  "SQL",
	"udo":                  "Csound",
	"ui":                   "XML",
	"unity":                "Unity3D Asset",
	"uno":                  "Uno",
	"upc":                  "Unified Parallel C",
	"uplc":                 "Untyped Plutus Core",
	"ur":                   "UrWeb",
	"urdf":                 "XML",
	"url":                  "INI",
	"urs":                  "UrWeb",
	"ux":                   "XML",
	"vala":                 "Vala",
	"vapi":                 "Vala",
	"vark":                 "Gosu",
	"vb":                   "Visual Basic .NET",
	"vbhtml":               "Visual Basic .NET",
	"vbproj":               "XML",
	"vbs":                  "VBScript",
	"vcl":                  "VCL",
	"vcxproj":              "XML",
	"vdf":                  "Valve Data Format",
	"veo":                  "Verilog",
	"vert":                 "GLSL",
	"vh":                   "SystemVerilog",
	"vhd":                  "VHDL",
	"vhdl":                 "VHDL",
	"vhf":                  "VHDL",
	"vhi":                  "VHDL",
	"vho":                  "VHDL",
	"vhs":                  "VHDL",
	"vht":                  "VHDL",
	"vhw":                  "VHDL",
	"vim":                  "Vim Script",
	"vimrc":                "Vim Script",
	"viw":                  "SQL",
	"vmb":                  "Vim Script",
	"vmf":                  "Valve Data Format",
	"volt":                 "Volt",
	"vrx":                  "GLSL",
	"vs":                   "GLSL",
	"vsh":                  "GLSL",
	"vshader":              "GLSL",
	"vsixmanifest":         "XML",
	"vssettings":           "XML",
	"vstemplate":           "XML",
	"vtl":                  "Velocity Template Language",
	"vto":                  "Vento",
	"vtt":                  "WebVTT",
	"vue":                  "Vue",
	"vw":                   "PLSQL",
	"vxml":                 "XML",
	"vy":                   "Vyper",
	"wast":                 "WebAssembly",
	"wat":                  "WebAssembly",
	"watchr":               "Ruby",
	"wdl":                  "WDL",
	"webapp":               "JSON",
	"webidl":               "WebIDL",
	"webmanifest":          "JSON",
	"weechatlog":           "IRC log",
	"wgsl":                 "WGSL",
	"whiley":               "Whiley",
	"wiki":                 "Wikitext",
	"wikitext":             "Wikitext",
	"wisp":                 "wisp",
	"wit":                  "WebAssembly Interface Type",
	"wixproj":              "XML",
	"wl":                   "Wolfram Language",
	"wlk":                  "Wollok",
	"wls":                  "Wolfram Language",
	"wlt":                  "Wolfram Language",
	"wlua":                 "Lua",
	"workbook":             "Markdown",
	"wren":                 "Wren",
	"ws":                   "Witcher Script",
	"wsdl":                 "XML",
	"wsf":                  "XML",
	"wsgi":                 "Python",
	"wxi":                  "XML",
	"wxl":                  "XML",
	"wxs":                  "XML",
	"x10":                  "X10",
	"x3d":                  "XML",
	"x68":                  "Motorola 68K Assembly",
	"xacro":                "XML",
	"xaml":                 "XML",
	"xbm":                  "X BitMap",
	"xc":                   "XC",
	"xdc":                  "Tcl",
	"xht":                  "HTML",
	"xhtml":                "HTML",
	"xi":                   "Logos",
	"xib":                  "XML",
	"xlf":                  "XML",
	"xliff":                "XML",
	"xm":                   "Logos",
	"xmi":                  "XML",
	"xml":                  "XML",
	"xml.dist":             "XML",
	"xmp":                  "XML",
	"xojo_code":            "Xojo",
	"xojo_menu":            "Xojo",
	"xojo_report":          "Xojo",
	"xojo_script":          "Xojo",
	"xojo_toolbar":         "Xojo",
	"xojo_window":          "Xojo",
	"xpl":                  "XProc",
	"xpm":                  "X PixMap",
	"xproc":                "XProc",
	"xproj":                "XML",
	"xpy":                  "Python",
	"xq":                   "XQuery",
	"xql":                  "XQuery",
	"xqm":                  "XQuery",
	"xquery":               "XQuery",
	"xqy":                  "XQuery",
	"xrl":                  "Erlang",
	"xs":                   "XS",
	"xsd":                  "XML",
	"xsh":                  "Xonsh",
	"xsjs":                 "JavaScript",
	"xsjslib":              "JavaScript",
	"xsl":                  "XSLT",
	"xslt":                 "XSLT",
	"xsp-config":           "XPages",
	"xsp.metadata":         "XPages",
	"xspec":                "XML",
	"xtend":                "Xtend",
	"xul":                  "XML",
	"xzap":                 "ZAP",
	"y":                    "Yacc",
	"yacc":                 "Yacc",
	"yaml-tmlanguage":      "YAML",
	"yaml.sed":             "YAML",
	"yang":                 "YANG",
	"yap":                  "Prolog",
	"yar":                  "YARA",
	"yara":                 "YARA",
	"yasnippet":            "YASnippet",
	"yml.mysql":            "YAML",
	"yrl":                  "Erlang",
	"yul":                  "Yul",
	"yyp":                  "JSON",
	"z3":                   "SMT",
	"zap":                  "ZAP",
	"zcml":                 "XML",
	"zed":                  "SpiceDB Schema",
	"zeek":                 "Zeek",
	"zep":                  "Zephir",
	"zig":                  "Zig",
	"zig.zon":              "Zig",
	"zil":                  "ZIL",
	"zimpl":                "Zimpl",
	"zmodel":               "Zmodel",
	"zmpl":                 "Zimpl",
	"zone":                 "DNS Zone",
	"zpl":                  "Zimpl",
	"zs":                   "ZenScript",
	"zsh":                  "Shell",
	"zsh-theme":            "Shell",
}
